// ===================================================================
// INTERACTIVES — the homepage widgets that respond to the visitor
// ===================================================================
// The share helpers, The Assay, You Draw It and The Receipt: JavaScript
// that only matters once someone scrolls to section 05, reaches the Assay
// under the contact form, or opens the footer receipt. You Draw It needs
// ai-carbon-data.js, which the loader fetches first. The calculator and
// Anatomy of a Prompt that were here are on carbon-ai.html.
//
// Loaded on demand by script.js (mks.load('interactives')), whose ON-DEMAND
// MODULES section says when, and why it declares nothing at the top level.
// ===================================================================

// ===================================
// SHARE HELPERS — let every interactive result leave with the visitor.
// Web Share where available (mobile), graceful fallbacks: images fall back to a
// download, text falls back to the clipboard. Every payload links home.
// ===================================
window.mks.share = (() => {
    const SITE = (location.hostname + location.pathname).replace(/\/+$/, '') || 'moseskolleh.github.io/sustaintheworld';
    // Restores the button's markup, not just its text: putting back
    // textContent dropped the icon for good. A second flash before the first
    // has finished keeps the original rather than saving "Copied ✓" as it.
    const flashing = new WeakMap();
    const flash = (btn, msg) => {
        if (!btn) return;
        const state = flashing.get(btn) || { html: btn.innerHTML };
        clearTimeout(state.timer);
        btn.textContent = msg;
        state.timer = setTimeout(() => { btn.innerHTML = state.html; flashing.delete(btn); }, 1700);
        flashing.set(btn, state);
    };
    return {
        site: SITE,
        async image(canvas, filename, text) {
            try {
                if (navigator.share && navigator.canShare) {
                    const blob = await new Promise(res => canvas.toBlob(res, 'image/png'));
                    if (blob) {
                        const file = new File([blob], filename, { type: 'image/png' });
                        if (navigator.canShare({ files: [file] })) {
                            try { await navigator.share({ files: [file], text: text || '' }); return; }
                            catch (e) { if (e && e.name === 'AbortError') return; }
                        }
                    }
                }
            } catch (e) { /* fall through to download */ }
            try {
                const a = document.createElement('a');
                a.href = canvas.toDataURL('image/png');
                a.download = filename;
                document.body.appendChild(a); a.click(); a.remove();
            } catch (e) { /* ignore */ }
        },
        async copy(str, btn) {
            try {
                if (navigator.clipboard && navigator.clipboard.writeText) {
                    await navigator.clipboard.writeText(str);
                    flash(btn, 'Copied ✓');
                    return;
                }
            } catch (e) { /* fall through to legacy path */ }
            try {
                const ta = document.createElement('textarea');
                ta.value = str; ta.style.position = 'fixed'; ta.style.opacity = '0';
                document.body.appendChild(ta); ta.focus(); ta.select();
                document.execCommand('copy'); ta.remove();
                flash(btn, 'Copied ✓');
            } catch (e) { flash(btn, 'Copy failed'); }
        }
    };
})();


// ===================================
// THE ASSAY — paste a JD, get a client-side fit grade, the evidence behind
// it, and the gaps. Deterministic matching over a hand-written rule set and
// the facts in content/profile.json: no AI, no model download, nothing
// leaves the browser — that restraint is the argument.
//
// Every requirement the site does not evidence is a gap, shown as
// prominently as a match; a hard gap caps the grade; and the top grade needs
// broad coverage of the ad (why: docs/plan.md, Phase 0 step 7). The rules
// are plain data so Phase 4 can move them into content/brief.json, where the
// validator can hold them to the case studies.
// ===================================
(() => {
    // ASSAY-FACTS:START — generated by scripts/build-content.js from content/profile.json. Do not edit by hand.
    const FACTS = {
        "languages": null,
        "experience": [
            {"title":"Researcher — Sustainable Artificial Intelligence","displayDates":"Sept 2025 — Present","start":"2025-09","end":null},
            {"title":"Cohort 7 Member — Sustainability Consulting Accelerator","displayDates":"Mar 2025 — Apr 2025","start":"2025-03","end":"2025-04"},
            {"title":"Climate Change Adaptation Intern","displayDates":"Jun 2023 — Oct 2023","start":"2023-06","end":"2023-10"},
            {"title":"Field Operations Manager","displayDates":"May 2019 — Sept 2019","start":"2019-05","end":"2019-09"},
            {"title":"Operations Supervisor","displayDates":"Sept 2018 — Apr 2019","start":"2018-09","end":"2019-04"}
        ],
        "degrees": ["MSc Environmental Sciences","MSc Industrial Engineering","BSc Honours Geology"]
    };
    // ASSAY-FACTS:END

    // Synonyms match whole words in any case, with an optional plural. A `re`
    // is a regular expression, alone or beside them, for the names only case
    // or punctuation tells apart from ordinary words: "SAP", "R" (not "R&D"),
    // "Excel", "LCA".
    const RULES = {
        minWords: 20,                                   // fewer, and there is nothing to grade honestly
        // `domain`: areas of this site's own field, not marked general below.
        // An HR or ERP ad used to grade High on general ones alone.
        high: { areas: 3, domain: 2, coverage: 0.6 },   // …and no hard gap at all
        workable: { areas: 2, domain: 1, coverage: 0.4, hardGaps: 1 },

        // A line with one of these asks for something even if nothing below
        // recognises it, and an unanswered one counts against coverage — the
        // thing that stops three matches in a long ad reading as a fit.
        // Stems: "manag" finds "management".
        requirementCues: ['experience', 'knowledge', 'skill', 'abilit', 'able to', 'degree', 'proficien',
            'familiar', 'understanding', 'background', 'expertise', 'you will', 'you\'ll', 'you have',
            'must', 'require', 'strong', 'proven', 'track record', 'responsib', 'manag', 'develop', 'lead',
            'support', 'deliver', 'conduct', 'analy', 'design', 'build', 'coordinat', 'prepar', 'writ',
            'qualif', 'certif', 'fluen', 'years', 'excellent', 'demonstrat', 'hands-on', 'master', 'bachelor'],
        // An unmet requirement on a line like this is listed but does not cap
        // the grade: the ad itself says it can do without it.
        softCues: ['a plus', 'nice to have', 'nice-to-have', 'desirable', 'preferred', 'preferably',
            'an advantage', 'advantageous', 'an asset', 'bonus', 'welcome', 'ideally', 'beneficial'],
        // Whole-line headings only: "Required: SAP" is a requirement.
        softHeading: '^(nice[- ]to[- ]haves?|preferred|desirable|bonus( points)?|pluses|good to have)( qualifications| skills)?\\s*:?$',
        hardHeading: '^(requirements?|required|must[- ]haves?|qualifications|what you bring|who you are|you have|your profile|profile|responsibilities|what you(\'ll| will) do)\\s*:?$',

        // Capability areas backed by delivered work, each with the evidence
        // and where on the site it is. A `general` one counts, never alone.
        strengths: [
            { label: 'ESG analysis & integration',
              syn: ['esg', 'environmental social', 'environmental, social', 'sustainability analyst', 'sustainability strategy', 'materiality', 'double materiality'],
              ev: [{ t: 'ESG Specialist Program certificate, Corporate Finance Institute (2024)', href: '#education' },
                   { t: 'Materiality assessments and transition planning in the OnePointFive accelerator', href: '#experience' }] },
            { label: 'Sustainability reporting (CSRD/ESRS & frameworks)',
              syn: ['csrd', 'esrs', 'sustainability report', 'sustainability reporting', 'non-financial report', 'disclosure', 'gri', 'sasb', 'ifrs s1', 'ifrs s2', 'tcfd', 'tnfd', 'cdp', 'sbti', 'reporting standard'],
              ev: [{ t: 'Framed the sustainable-AI assessment framework against CSRD/ESRS disclosure logic', href: 'case-studies.html#sustainable-ai' },
                   { t: 'SBTi, CDP, GHG Protocol, IFRS S1&S2, TCFD and TNFD covered in the OnePointFive accelerator', href: '#experience' }] },
            { label: 'GHG accounting & carbon footprinting',
              syn: ['ghg', 'greenhouse gas', 'scope 1', 'scope 2', 'scope 3', 'carbon accounting', 'carbon footprint', 'emissions inventory', 'ghg protocol'],
              ev: [{ t: 'Mapped generative AI’s footprint from Scope 2 electricity to Scope 3 hardware and cooling water', href: 'case-studies.html#sustainable-ai' },
                   { t: 'EcoPrompt Coach: energy, water and carbon per AI query, every factor sourced', href: 'carbon-ai.html' }] },
            { label: 'Climate risk, adaptation & disaster resilience',
              syn: ['climate risk', 'climate adaptation', 'resilience', 'physical risk', 'transition risk', 'disaster risk', 'hazard', 'vulnerability', 'sendai'],
              ev: [{ t: 'UNDRR: documented 54 global hazard information systems for the Sendai Framework', href: 'case-studies.html#un-disaster' },
                   { t: 'Flood-risk and adaptation consultancy for Wuppertal (academic consultancy)', href: 'case-studies.html#wuppertal' }] },
            { label: 'Water resources, hydrogeology & WASH',
              syn: ['wash', 'hydrogeology', 'groundwater', 'aquifer', 'borehole', 'water resource', 'water supply', 'water management', 'water sector', 'water security', 'drinking water', 'water point', 'hydrology', 'sanitation'],
              ev: [{ t: '164 water points in Sierra Leone: 100 wells rehabilitated, 50 boreholes built, 14 solar-powered', href: '#experience' },
                   { t: '70% aquifer strike rate using electrical-resistivity surveys', href: 'case-studies.html#groundwater' },
                   { t: 'Soft-path water management for Freetown (MSc thesis)', href: 'case-studies.html#water-management' }] },
            { label: 'GIS & geospatial analysis',
              syn: ['gis', 'qgis', 'arcgis', 'geospatial', 'spatial analysis', 'spatial data', 'remote sensing', 'cartography', 'hazard mapping', 'flood mapping', 'groundwater mapping'],
              ev: [{ t: 'GIS groundwater-potential maps of the Freetown Complex, validated by drilling', href: 'case-studies.html#groundwater' },
                   { t: 'Flood-risk assessment with GIS for Wuppertal', href: 'case-studies.html#wuppertal' }] },
            { label: 'Data analysis & visualization', general: true,
              syn: ['python', 'data analysis', 'data analytics', 'pandas', 'sql', 'statistic', 'tableau', 'power bi', 'data visualization', 'data visualisation', 'r programming'],
              ev: [{ t: 'Python for the global river-export pollution analysis (MSc thesis)', href: '#skills' },
                   { t: 'Google Advanced Data Analytics certificate (2024)', href: '#education' }] },
            { label: 'Sustainable AI & AI governance',
              syn: ['sustainable ai', 'ai governance', 'responsible ai', 'ai ethics', 'green ai', 'ai sustainability', 'generative ai', 'llm'],
              ev: [{ t: 'Researcher, Sustainable AI at the Digital Society School, with the Ministry of Finance as partner', href: 'case-studies.html#sustainable-ai' },
                   { t: 'EcoPrompt Coach: the public, runnable companion to the research prototype', href: 'carbon-ai.html' }] },
            { label: 'Water quality & environmental modelling',
              syn: ['pollution', 'water quality', 'contamination', 'nutrient', 'nitrogen', 'effluent', 'catchment', 'watershed', 'eutrophication', 'environmental modelling', 'environmental modeling'],
              ev: [{ t: 'MARINA-Multi pollution modelling across 10,226 sub-basins (MSc thesis)', href: 'case-studies.html#coastal' },
                   { t: 'Future storylines for African coastal water pollution', href: 'case-studies.html#coastal' }] },
            { label: 'Stakeholder engagement & facilitation', general: true,
              syn: ['stakeholder', 'facilitation', 'facilitate', 'workshop', 'engagement', 'cross-functional', 'interdisciplinary', 'capacity building', 'collaboration', 'community', 'communities'],
              ev: [{ t: 'Facilitated stakeholder workshops on flood vulnerability in Wuppertal', href: 'case-studies.html#wuppertal' },
                   { t: 'Tested the sustainable-AI prototype with managers and staff in public research sessions', href: 'case-studies.html#sustainable-ai' }] },
            { label: 'Field operations & project delivery', general: true,
              syn: ['project management', 'project delivery', 'project manager', 'field operations', 'operations management', 'programme management', 'program management', 'drilling'],
              ev: [{ t: 'Field Operations Manager: completion of 14 solar-powered boreholes, Sierra Leone', href: '#experience' },
                   { t: 'Operations Supervisor: 50 boreholes built and 100 hand-dug wells rehabilitated', href: '#experience' }] },
            { label: 'International & cross-cultural work', general: true,
              syn: ['international', 'multicultural', 'cross-cultural', 'multilingual', 'global south', 'developing country', 'developing countries', 'emerging market', 'fieldwork', 'field work'],
              ev: [{ t: 'Studied or worked in Sierra Leone, China, Germany and the Netherlands', href: '#experience' },
                   { t: 'Full Chinese Government MOFCOM scholarship, Hunan University', href: '#education' }] },
            { label: 'Applied research & methodology', general: true,
              syn: ['research', 'researcher', 'thesis', 'peer-review', 'methodology', 'literature review', 'academic', 'msc'],
              ev: [{ t: 'MSc Environmental Sciences (Wageningen) and MSc Industrial Engineering (Hunan)', href: '#education' },
                   { t: 'Research outputs, with how to reproduce them', href: 'research.html' }] }
        ],

        // Named methods, tools and platforms: matched only where this page
        // shows the tool (toolEvidence below), a gap anywhere else. A bare
        // name matches itself in any case.
        tools: ['Workiva', 'Enablon', 'Sphera', 'Persefoni', 'Novisto', 'Tableau', 'Python', 'QGIS', 'MATLAB',
            'SPSS', 'Stata', 'SimaPro', 'openLCA', 'GaBi', 'JavaScript', 'Machine learning',
            { name: 'SAP', re: '\\bSAP\\b' },
            { name: 'Excel', re: '\\bExcel\\b' },
            { name: 'R', re: '\\bR\\b(?![&+\'’-])|\\bRStudio\\b' },
            { name: 'Salesforce Net Zero Cloud', syn: ['net zero cloud', 'salesforce'] },
            { name: 'Microsoft Sustainability Manager', syn: ['microsoft sustainability manager', 'microsoft cloud for sustainability'] },
            { name: 'Watershed', syn: ['watershed platform', 'watershed climate'] },
            { name: 'Power BI', syn: ['power bi', 'powerbi'] },
            { name: 'SQL', syn: ['sql', 'postgresql', 'mysql'] },
            { name: 'ArcGIS', syn: ['arcgis', 'esri'] },
            { name: 'Google Earth Engine', syn: ['earth engine'] },
            { name: 'Life Cycle Assessment', re: '\\bLCAs?\\b', syn: ['life cycle assessment', 'life-cycle assessment', 'lifecycle assessment', 'life cycle analysis'] }],

        // content/profile.json records no languages today, so each one an
        // ad asks for is a gap until it does. English, the site's own, is not
        // a gap, but its level is not stated either: until it is, it is one
        // to confirm, and a line asking only for it is not graded.
        languages: ['German', 'Portuguese', 'Italian', 'Arabic', 'Japanese', 'Swedish', 'Danish', 'Norwegian', 'Polish',
            { name: 'Dutch', syn: ['dutch', 'nederlands', 'flemish'] },
            { name: 'French', syn: ['french', 'français', 'francais'] },
            { name: 'Spanish', syn: ['spanish', 'español', 'espanol'] },
            { name: 'Mandarin', syn: ['mandarin', 'chinese'] },
            { name: 'English', syn: ['english'], confirm: 'Level of English' }],
        // "Dutch" on a line about a ministry is a nationality. On a line with
        // one of these, or of four words or fewer, it is a language; a clause
        // over four words needs its own ("…German partners, in fluent
        // English" asks for English alone). A clause of languages only runs
        // on past its comma: "German, French or Spanish at C1".
        languageCues: ['fluent', 'fluency', 'native', 'mother tongue', 'proficient', 'proficiency', 'speak',
            'speaking', 'speaker', 'spoken', 'written', 'verbal', 'language', 'bilingual', 'command of',
            'working knowledge', 'english', 'vloeiend'],
        // The language to write an application in is not one the job needs:
        // "Applications in English or Dutch are welcome".
        applyIn: ['apply in', 'application in', 'applications in', 'cv in', 'letter in'],
        // Never when the next word starts with one of these, or is a name
        // ("Dutch Tax Authority"): that is the employer, not the job.
        nationalStems: ['minist', 'govern', 'federal', 'national', 'tax', 'authorit', 'agenc', 'municipal', 'compan',
            'firm', 'office', 'client', 'customer', 'partner', 'market', 'organi', 'team', 'colleague', 'bank', 'law',
            'legislat', 'regulat', 'polic', 'public', 'sector', 'business', 'cultur', 'passport', 'univers',
            'region', 'cit', 'water', 'energy', 'stakeholder'],
        // Highest first: the first that matches a line is the level it asks
        // for. CEFR codes match in capitals only. No level stated means B2.
        levels: [
            { level: 7, label: 'native', re: '\\b(?:native|mother tongue|bilingual)\\b', flags: 'i' },
            { level: 6, label: 'C2', re: '\\bC2\\b' },
            { level: 5, label: 'C1 / fluent', re: '\\bC1\\b|\\b(?:fluent|fluency|vloeiend|excellent|full professional|professional working)\\b', flags: 'i' },
            { level: 4, label: 'B2', re: '\\bB2\\b|\\b(?:business[- ]level|good command|very good)\\b', flags: 'i' },
            { level: 3, label: 'B1', re: '\\bB1\\b|\\b(?:working knowledge|conversational|intermediate)\\b', flags: 'i' },
            { level: 2, label: 'A2', re: '\\bA2\\b|\\b(?:basic|elementary)\\b', flags: 'i' },
            { level: 1, label: 'A1', re: '\\bA1\\b' }
        ],
        defaultLevel: 4,

        // "5+ years", "minimum of 7 years", "at least three years", "3-5
        // years" (the lower bound). "5+" or "at least 5" is a requirement
        // anywhere; a bare "3 years", or "over 20 years", only beside an
        // experience cue or under a requirements heading. Never on a line
        // about the contract or the calendar, nor where the employer talks
        // about itself ("For over 20 years, we have…"), not to the applicant.
        years: {
            re: '(at least|minimum(?: of)?|min\\.?)?\\s*\\b(\\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten|twelve|fifteen|twenty)\\s*(\\+|plus)?\\s*(?:(?:-|–|to)\\s*\\d{1,2}\\s*\\+?\\s*)?years?\\b',
            cue: ['experience', 'experienced', 'background', 'track record', 'working', 'similar role', 'relevant', 'professional', 'senior', 'industry', 'sector', 'field'],
            not: ['contract', 'duration', 'ago', 'fixed-term', 'fixed term', 'old', 'of age', 'per year'],
            we: ['we', 'our', 'founded'],
            you: ['you', 'candidate', 'applicant', 'someone', 'looking for', 'seek', 'expect', 'requir', 'need', 'ideal', 'must', 'should'],
            words: { one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, twelve: 12, fifteen: 15, twenty: 20 }
        },
        // Years are counted from content/profile.json, professional roles
        // only: a title with one of these is training or a placement.
        notCountedAsYears: ['intern', 'internship', 'cohort', 'accelerator', 'trainee', 'volunteer', 'student'],

        // Hard requirements the site cannot show, beyond tools, languages
        // and years. `cue` must also be on the line, so "As one of the Big
        // Four, we…" is not a demand; `not` rules a line out; {degrees} is
        // filled from content/profile.json.
        gaps: [
            { label: 'Big Four / consulting-firm experience',
              re: '\\bbig (?:four|4)\\b|\\bdeloitte\\b|\\bpwc\\b|pricewaterhouse|\\bkpmg\\b|ernst ?& ?young|\\bEY\\b|\\baccenture\\b|\\bmckinsey\\b|boston consulting|\\bBCG\\b|management consult|consult(?:ing|ancy) (?:firm|experience)',
              flags: 'i',
              cue: ['experience', 'background', 'years', 'worked', 'track record', 'previous', 'prior', 'alumni'],
              text: 'Not evidenced on this site: the consulting on it is an academic consultancy project (Wuppertal) and an accelerator cohort (OnePointFive), not employment at a consulting firm. Ask Moses.' },
            { label: 'Director / head-of level',
              syn: ['senior director', 'head of sustainability', 'head of esg', 'vice president', 'principal consultant', 'managing director', 'director level', 'director-level'],
              not: ['report to', 'reporting to', 'reports to', 'work with', 'working with'],
              text: 'No role at that level is listed on this site. Ask Moses.' },
            { label: 'Financial modelling / valuation',
              syn: ['financial model', 'financial modeling', 'financial modelling', 'valuation', 'cfa', 'equity research', 'fp&a'],
              text: 'Not evidenced on this site; the analysis here is environmental, not financial. Ask Moses.' },
            { label: 'A PhD',
              syn: ['phd required', 'doctorate required', 'phd in', 'phd degree', 'doctoral degree'],
              not: ['msc or', 'master or', 'master\'s or', 'masters or', 'or phd', 'or a phd'],
              text: 'Not evidenced on this site; the degrees listed are {degrees}. Ask Moses.' },
            { label: 'A law degree',
              syn: ['attorney', 'law degree', 'legal counsel', 'regulatory lawyer', 'bar admission', 'qualified lawyer'],
              text: 'Not evidenced on this site; the degrees listed are {degrees}. Ask Moses.' }
        ],

        // Facts only Moses can state. Never graded, always listed.
        confirm: [
            { label: 'Right to work', syn: ['right to work', 'work permit', 'eligible to work', 'authorised to work', 'authorized to work', 'work authorisation', 'work authorization', 'residence permit', 'eu citizen', 'eu citizenship', 'eu passport'] },
            { label: 'Visa sponsorship', syn: ['visa', 'sponsorship', 'kennismigrant', 'highly skilled migrant'] },
            { label: 'Security clearance', syn: ['security clearance', 'sc clearance', 'dv clearance', 'security vetting', 'background check', 'certificate of conduct', 'vog'] },
            { label: 'Driving licence', syn: ['driving licence', 'driving license', 'driver\'s licence', 'driver\'s license', 'drivers licence', 'drivers license'] },
            { label: 'Relocation', syn: ['relocate', 'relocation', 'willing to move'] }
        ]
    };

    // --- Matching ----------------------------------------------------------
    const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const escHtml = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    const cache = new Map();
    const rx = (source, flags) => {
        const key = source + '/' + (flags || '');
        if (!cache.has(key)) cache.set(key, new RegExp(source, flags || ''));
        return cache.get(key);
    };
    // Whole words, so "gis" does not match inside "logistics".
    const hit = (text, syns) => !!(syns && syns.length) &&
        rx('(?:^|[^\\w])(?:' + syns.map(esc).join('|') + ')(?:s|es)?(?!\\w)', 'i').test(text);
    const stemHit = (text, stems) => rx('\\b(?:' + stems.map(esc).join('|') + ')', 'i').test(text);
    const matches = (text, rule) => (!!rule.re && rx(rule.re, rule.flags).test(text)) || hit(text, rule.syn);
    const named = (x) => (typeof x === 'string' ? { name: x, syn: [x.toLowerCase()] } : x);
    const TOOLS = RULES.tools.map(named);
    const LANGUAGES = RULES.languages.map(named);
    const LANG_ALT = LANGUAGES.reduce((a, l) => a.concat(l.syn), []).map(esc).join('|');
    const langCue = (text) => hit(text, RULES.languageCues) || /\b[ABC][12]\b/.test(text);
    const wordCount = (text) => text.trim().split(/\s+/).length;
    const langOnly = (text) => !text.replace(rx('\\b(?:' + LANG_ALT + '|and|or)\\b|[\\s/&().-]', 'gi'), '');
    const clauses = (line) => line.split(/[,;]/).reduce((out, c) => {
        if (out.length && langOnly(out[out.length - 1])) out[out.length - 1] += ',' + c; else out.push(c);
        return out;
    }, []);
    // A language, or a nationality? Past any list of languages ("German and
    // French partners"), the next word decides.
    const spoken = (clause, lang) => {
        const at = rx('(?:^|[^\\w])(?:' + lang.syn.map(esc).join('|') + ')(?!\\w)', 'gi');
        return Array.from(clause.matchAll(at)).some((m) => {
            const rest = clause.slice(m.index + m[0].length)
                .replace(rx('^(?:\\s*(?:,|/|&|and|or)\\s*(?:' + LANG_ALT + '))*', 'i'), '');
            const [, next = '', after = ''] = rest.match(/^\s+(\S+)(?:\s+(\S+))?/) || [];
            const name = /^[A-Z][a-z]/.test(next) && !langCue(next) && (/^[A-Z]/.test(after) || after === 'of');
            return !stemHit(next, RULES.nationalStems) && !name;
        });
    };
    const listJoin = (a) => (a.length < 2 ? a.join('') : `${a.slice(0, -1).join(', ')} and ${a[a.length - 1]}`);
    const plural = (n, word) => `${n} ${word}${n === 1 ? '' : 's'}`;

    // Where this page shows a tool, best proof first: the skills toolkit
    // (it carries a proof line), then the experience bullets, the project
    // tags, the courses and the skill lists. Read from the page itself, so a
    // tool the page stops showing stops being matched.
    const clean = (el) => (el ? el.textContent.replace(/\s+/g, ' ').trim() : '');
    const up = (el, sel, inner) => clean(el.closest(sel) && el.closest(sel).querySelector(inner));
    const SOURCES = [
        ['#skills .toolkit-name', '#skills', (el) => `Skills: ${up(el, '.toolkit-item', '.toolkit-proof') || clean(el)}`],
        ['#experience li', '#experience', (el) => clean(el) + (up(el, '.timeline-content', 'h3') ? ` (${up(el, '.timeline-content', 'h3')})` : '')],
        ['#projects .project-tech span', '#projects', (el) => `Listed as a tool on the ${up(el, '.project-card', 'h3')} project`],
        ['#education li, #education .cert-line', '#education', (el) => `Covered in ${up(el, '.education-card', 'h3, .cert-title')}: ${clean(el)}`],
        ['#skills .skills-checklist li, #skills .frameworks-list li', '#skills', () => 'Listed under Skills & Education']
    ];
    function toolEvidence(tool, doc) {
        for (const [sel, href, say] of (doc ? SOURCES : [])) {
            const el = Array.from(doc.querySelectorAll(sel)).find(e => matches(clean(e), tool));
            if (el) return [{ t: say(el), href }];
        }
        return null;
    }

    // One line per requirement: a bullet, a sentence, a semicolon clause —
    // and "·", so "Fluent Dutch · 5+ years Big Four · SAP" is three.
    const splitLines = (raw) => raw
        .replace(/([.!?])\s+(?=[A-Z0-9(])/g, '$1\n')
        .split(/[\n\r;•·▪►]+/)
        .map(l => l.replace(/^\s*(?:[-–—*]+|\d{1,2}[.)])\s+/, '').trim())
        .filter(Boolean);

    const levelOf = (text) => RULES.levels.find(l => rx(l.re, l.flags).test(text)) || null;
    const month = (ym) => { const [y, m] = String(ym).split('-').map(Number); return y * 12 + m - 1; };
    const duration = (months) => {
        const y = Math.floor(months / 12);
        const m = months % 12;
        return y ? plural(y, 'year') + (m ? ' ' + plural(m, 'month') : '') : plural(m, 'month');
    };

    // Professional experience from content/profile.json, counted the
    // conservative way: each role from its first month to its last ("May
    // 2019 — Sept 2019" is four months, mid-month to mid-month), an open
    // role to this month, and internships, programmes and study not at all.
    function experienceCount(facts, now) {
        const skip = rx('\\b(?:' + RULES.notCountedAsYears.join('|') + ')\\b', 'i');
        const roles = facts.experience || [];
        const counted = roles.filter(r => !skip.test(r.title));
        const current = now.getFullYear() * 12 + now.getMonth();
        const months = counted.reduce((n, r) => n + Math.max(0, (r.end ? month(r.end) : current) - month(r.start)), 0);
        return { months, counted, skipped: roles.filter(r => skip.test(r.title)) };
    }

    /**
     * The whole assessment, as data. Pure apart from reading the page for
     * tool evidence; `opts.facts`, `opts.now` and `opts.doc` let a test pin
     * all three.
     */
    function analyse(raw, opts) {
        const o = opts || {};
        const facts = o.facts || FACTS;
        const doc = 'doc' in o ? o.doc : document;
        const text = String(raw || '');
        const words = (text.match(/[A-Za-z0-9À-ÿ][\w'’&+-]*/g) || []).length;
        if (words < RULES.minWords) return { status: words ? 'short' : 'empty', words };

        const exp = experienceCount(facts, o.now || new Date());
        const degrees = listJoin(facts.degrees || []) || 'not listed';
        const seen = {};
        const matched = [];     // capability areas, with their evidence
        const met = [];         // named requirements the site evidences
        const gaps = [];        // …and the ones it does not
        const confirm = [];
        const toolEv = {};
        let softSection = false;
        let reqSection = false;
        let asked = 0;
        let answered = 0;

        splitLines(text).forEach((line) => {
            const n = line.split(/\s+/).length;
            // A heading ("Requirements:", "Nice to have") asks for nothing
            // itself, but a soft one makes every line under it soft.
            const heading = /:$/.test(line);
            if (heading || n <= 4) {
                if (rx(RULES.softHeading, 'i').test(line)) { softSection = true; reqSection = false; return; }
                if (rx(RULES.hardHeading, 'i').test(line)) {
                    // Under "Responsibilities", years are the job's.
                    softSection = false;
                    reqSection = !/^(?:respons|what you(?:'ll| will) do)/i.test(line);
                    return;
                }
                if (heading) return;
            }
            const soft = softSection || hit(line, RULES.softCues);
            let recognised = false;
            let covered = false;
            let missing = false;
            let toConfirm = false;
            // One named requirement: met, with its evidence, or a gap. Asked
            // twice, it is listed once, hard if either time was.
            const need = (key, label, ev, note) => {
                recognised = true;
                if (ev) {
                    covered = true;
                    if (!seen[key]) met.push(seen[key] = { label, ev });
                    return;
                }
                missing = missing || !soft;
                if (!seen[key]) gaps.push(seen[key] = { label, text: note, hard: false });
                seen[key].hard = seen[key].hard || !soft;
            };

            RULES.strengths.forEach((s) => {
                if (!hit(line, s.syn)) return;
                recognised = covered = true;
                if (!seen[s.label]) matched.push(seen[s.label] = s);
            });

            TOOLS.forEach((tool) => {
                if (!matches(line, tool)) return;
                if (!(tool.name in toolEv)) toolEv[tool.name] = toolEvidence(tool, doc);
                need('tool:' + tool.name, tool.name, toolEv[tool.name], 'Not evidenced on this site. Ask Moses.');
            });

            // The employer describing itself ("Our team works in English,
            // Dutch and French") asks nothing of the applicant, and nor does
            // the language to apply in. In the employer's voice a language is
            // asked for only where the line says so: a level, "a plus", or
            // "language" in its clause ("Our working language is Dutch").
            const Y = RULES.years;
            const ours = hit(line, Y.we) && !stemHit(line, Y.you);
            const asks = (clause) => !ours || levelOf(line) || hit(line, RULES.softCues) || hit(clause, ['language']);
            if ((n <= 4 || langCue(line)) && !hit(line, RULES.applyIn)) {
                clauses(line).forEach((clause) => {
                    if ((wordCount(clause) > 4 && !langCue(clause)) || !asks(clause)) return;
                    LANGUAGES.forEach((lang) => {
                        if (!spoken(clause, lang)) return;
                        // The level beside this language, else its clause's:
                        // "Native German, business-level French" asks for two.
                        const want = levelOf(clause.split(/\/|\band\b/i).find(seg => hit(seg, lang.syn)) || '') || levelOf(clause);
                        const has = (facts.languages || []).find(l => hit(String(l.language), lang.syn));
                        if (lang.confirm && !has) {
                            toConfirm = true;
                            if (!seen[lang.confirm]) confirm.push(seen[lang.confirm] = lang.confirm);
                            return;
                        }
                        const hasLevel = has && levelOf(String(has.level));
                        const ok = hasLevel && hasLevel.level >= (want ? want.level : RULES.defaultLevel);
                        need(`lang:${lang.name}:${want ? want.level : ''}`, lang.name + (want ? ` (${want.label})` : ''),
                            ok && [{ t: `${lang.name} at ${has.level}, as listed on this site` }],
                            has ? `The level listed on this site is ${has.level}. Ask Moses.` : 'Not evidenced on this site. Ask Moses.');
                    });
                });
            }

            if (!hit(line, Y.not) && !ours) {
                let years = 0;
                for (const m of line.matchAll(rx(Y.re, 'gi'))) {
                    const count = Number(m[2]) || Y.words[m[2].toLowerCase()] || 0;
                    if (m[1] || m[3] || reqSection || hit(line, Y.cue)) years = Math.max(years, count);
                }
                if (years) {
                    const have = duration(exp.months);
                    need('years:' + years, `${years}+ year${years === 1 ? '' : 's'} of experience`,
                        exp.months >= years * 12 && [{ t: `About ${have} across the professional roles listed on this site (internships, programmes and study not counted)`, href: '#experience' }],
                        `About ${have}, counting the professional roles listed on this site: ${listJoin(exp.counted.map(r => `${r.title} (${r.displayDates})`))}. ` +
                        `Not counted: ${listJoin(exp.skipped.map(r => r.title).concat('full-time study'))}. Ask Moses.`);
                }
            }

            RULES.gaps.forEach((g) => {
                if (!matches(line, g) || (g.cue && !hit(line, g.cue)) || hit(line, g.not)) return;
                need('gap:' + g.label, g.label, null, g.text.replace('{degrees}', degrees));
            });

            RULES.confirm.forEach((c) => {
                if (!hit(line, c.syn)) return;
                toConfirm = true;
                if (!seen[c.label]) confirm.push(seen[c.label] = c.label);
            });

            // Coverage: of the lines that ask for something, how many does
            // the site answer? A line with a hard gap is not answered, whatever
            // else it mentions; a line that only asks for something to
            // confirm (right to work, say) is not graded at all.
            if (toConfirm && !recognised) return;
            if (recognised || stemHit(line, RULES.requirementCues)) {
                asked++;
                if (covered && !missing) answered++;
            }
        });

        const hard = gaps.filter(g => g.hard);
        const areas = matched.length;
        const domain = matched.filter(m => !m.general).length;
        const share = asked ? answered / asked : 0;
        const lines = `${answered} of ${plural(asked, 'requirement line')}`;
        const fits = (bar) => areas >= bar.areas && domain >= bar.domain && share >= bar.coverage;
        let grade, cls, blurb;
        if (!domain) {
            grade = 'Different field'; cls = 'marginal';
            blurb = (areas || met.length ? 'Only general skills match: nothing' : 'Nothing') +
                ' here maps to the environmental, climate or sustainability work on this site. Most likely a different field.';
        } else if (!hard.length && fits(RULES.high)) {
            grade = 'High-grade match'; cls = 'high';
            blurb = `${plural(areas, 'area')} of this ad map to delivered work on this site, answering ${lines}, with no hard gaps.`;
        } else if (hard.length <= RULES.workable.hardGaps && fits(RULES.workable)) {
            grade = 'Workable match'; cls = 'workable';
            blurb = `${plural(areas, 'area')} map to delivered work, answering ${lines}` +
                (hard.length ? ', but one requirement is not evidenced here; it is listed first.' : '.');
        } else {
            grade = 'Marginal match'; cls = 'marginal';
            blurb = hard.length > 1
                ? `The work overlaps in ${plural(areas, 'area')}, but ${hard.length} hard requirements are not evidenced on this site. Read the gaps first.`
                : (areas >= RULES.workable.areas
                    ? `${plural(areas, 'area')} map to delivered work, but the site answers only ${lines}`
                    : `Only ${plural(areas, 'area')} maps to delivered work, answering ${lines}`) +
                  (hard.length ? ', and one hard requirement is not evidenced here.' : '. Worth a conversation only if the rest can be learned on the job.');
        }
        if (confirm.length) blurb += ` Still to confirm: ${listJoin(confirm.map(c => c[0].toLowerCase() + c.slice(1)))}.`;

        return {
            status: 'graded', words, grade, cls, blurb, matched, met, confirm, hard,
            gaps: hard.concat(gaps.filter(g => !g.hard)),
            coverage: { answered, asked },
            experience: exp
        };
    }

    // For the tests, and for The Brief (Phase 4) to build on.
    window.mks.assay = { analyse, RULES, FACTS };

    // --- The page -------------------------------------------------------------
    const input = document.getElementById('assayInput');
    const runBtn = document.getElementById('assayRun');
    const clearBtn = document.getElementById('assayClear');
    const result = document.getElementById('assayResult');
    if (!input || !runBtn || !result) return;
    let lastAssayText = '';

    const row = (label, body, cls) => `<div class="assay-row${cls ? ' ' + cls : ''}"><div class="assay-req">${label}</div><div class="assay-ev">${body}</div></div>`;
    const block = (cls, heading, rows) => (rows.length
        ? `<div class="assay-map ${cls}"><div class="mono-label assay-map-h">${heading}</div>${rows.join('')}</div>` : '');
    const evidence = (list) => list.map(e => (e.href
        ? `<a href="${escHtml(e.href)}">${escHtml(e.t)}</a>`
        : `<span>${escHtml(e.t)}</span>`)).join('');

    const assay = () => {
        const a = analyse(input.value);
        result.hidden = false;
        if (a.status !== 'graded') {
            result.innerHTML = a.status === 'empty'
                ? '<p class="assay-empty">Paste a job description first. The requirements section is the part that matters.</p>'
                : `<p class="assay-empty">That is ${plural(a.words, 'word')}, too few to grade honestly. Paste the requirements section: ${RULES.minWords} words or more.</p>`;
            if (clearBtn) clearBtn.hidden = a.status === 'empty';
            return;
        }

        const found = a.met.concat(a.matched);
        const matchHtml = block('assay-matches', 'What you asked for → what backs it',
            found.map(m => row(escHtml(m.label), evidence(m.ev))));
        const gapHtml = block('assay-gaps', 'Gaps — what this site does not show', a.gaps.map(g => row(
            escHtml(g.label) + (g.hard ? '' : ' <span class="assay-soft">nice to have</span>'),
            `<span class="assay-miss">${escHtml(g.text)}</span>`, 'assay-row-gap')));
        let html = `<div class="assay-grade assay-grade-${a.cls}"><span class="assay-grade-tag">${a.grade}</span><p>${escHtml(a.blurb)}</p></div>`;
        // Hard gaps explain a capped grade, so they come before the matches
        // that would otherwise bury them. With none, the matches lead.
        html += a.hard.length ? gapHtml + matchHtml : matchHtml + gapHtml;
        html += block('assay-confirm', 'Confirm with Moses — not stated on this site',
            a.confirm.map(c => row(escHtml(c), '<span class="assay-ask">Not stated on this site. Confirm with Moses.</span>', 'assay-row-gap')));

        if (a.cls === 'high' || a.cls === 'workable') {
            const subject = encodeURIComponent(`Fit for your role — ${found.length} matching areas`);
            const body = encodeURIComponent(`Hi Moses,\n\nI ran your in-browser fit-check against a role and it flagged ${found.length} matching areas${a.gaps.length ? ` (and ${plural(a.gaps.length, 'gap')})` : ''}. I'd like to talk.\n\n`);
            html += `<div class="assay-cta-wrap"><a class="btn btn-primary btn-small" href="mailto:moseskollehsesay@gmail.com?subject=${subject}&body=${body}" data-analytics="assay-contact"><svg class="icon" aria-hidden="true"><use href="#i-paper-plane"></use></svg> This looks like a fit — get in touch</a></div>`;
        }
        // Plain-text version a recruiter can copy into notes or an email.
        let plain = `Moses Kolleh Sesay — fit assessment: ${a.grade}\n${a.blurb}\n`;
        if (a.gaps.length) plain += '\nGaps (not shown on the site):\n' + a.gaps.map(g => `• ${g.label}${g.hard ? '' : ' (nice to have)'}: ${g.text}\n`).join('');
        if (found.length) plain += '\nWhat backs the rest:\n' + found.map(t => `• ${t.label}\n` + t.ev.map(e => `   - ${e.t}\n`).join('')).join('');
        if (a.confirm.length) plain += '\nConfirm with Moses (not stated on the site):\n' + a.confirm.map(c => `• ${c}\n`).join('');
        lastAssayText = plain + `\n— ${window.mks.share ? window.mks.share.site : 'moseskolleh.github.io/sustaintheworld'}`;
        html += `<div class="assay-copy-wrap"><button type="button" class="btn btn-secondary btn-small assay-copy" data-analytics="assay-copy"><svg class="icon" aria-hidden="true"><use href="#i-copy"></use></svg> Copy this result</button></div>`;
        html += '<p class="assay-note">Deterministic matching against a hand-written evidence set and the facts on this site: no AI; the ad is never sent. Anything the site does not show is a gap, not a guess. A starting point for a conversation, not a verdict.</p>';
        result.innerHTML = html;
        document.dispatchEvent(new CustomEvent('mks:layout'));   // new links, for back to top to keep clear of
        if (clearBtn) clearBtn.hidden = false;
        // count.js records the grade (never the ad); with count.js blocked
        // there is no mks.track, and nothing to record it in.
        if (typeof window.mks.track === 'function') window.mks.track('assay-' + a.cls);
    };

    runBtn.addEventListener('click', assay);
    result.addEventListener('click', (e) => {
        const b = e.target.closest('.assay-copy');
        if (b && window.mks.share) window.mks.share.copy(lastAssayText, b);
    });
    if (clearBtn) {
        clearBtn.addEventListener('click', () => {
            input.value = '';
            result.hidden = true;
            result.innerHTML = '';
            clearBtn.hidden = true;
            input.focus();
        });
    }

    // Instant demo: sample roles inject a realistic JD and grade it.
    const SAMPLES = {
        esg: 'ESG Analyst — support CSRD and ESRS reporting, build our GHG inventory across Scope 1, 2 and 3, run sustainability data analysis, and engage stakeholders across the business. Familiarity with GRI, TCFD and SBTi a plus.',
        climate: 'Climate Risk Consultant — assess physical and transition climate risk, build resilience and adaptation plans, analyse hazard and vulnerability data, and facilitate stakeholder workshops. GIS and scenario analysis welcome.',
        water: 'WASH Programme Officer — manage borehole drilling and groundwater projects, run hydrogeology surveys, produce GIS maps, and coordinate community water delivery in developing countries.'
    };
    document.querySelectorAll('.assay-sample').forEach(b => {
        b.addEventListener('click', () => {
            input.value = SAMPLES[b.getAttribute('data-sample')] || '';
            assay();
            result.scrollIntoView({ behavior: window.mks.scrollMotion(), block: 'nearest' });
        });
    });
})();


// ===================================
// YOU DRAW IT — predict AI's hidden energy curve, then reveal the estimates
// The NYT "you draw it" mechanic, powered by the shared AI carbon data.
// ===================================
(() => {
    const svg = document.getElementById('ydiSvg');
    const revealBtn = document.getElementById('ydiReveal');
    const resetBtn = document.getElementById('ydiReset');
    const verdictEl = document.getElementById('ydiVerdict');
    const hintEl = document.getElementById('ydiHint');
    const tableEl = document.getElementById('ydiTable');
    const shareBtn = document.getElementById('ydiShare');
    const cardCanvas = document.getElementById('ydiCardCanvas');
    const legendEl = document.getElementById('ydiLegend');
    const DATA = (typeof window !== 'undefined') ? window.AICarbonData : null;
    if (!svg || !revealBtn || !DATA) return;
    let cardData = null;

    const set = (e, attrs) => {
        for (const k in attrs) e.setAttribute(k, attrs[k]);
        return e;
    };
    // A group, not an image (which may hold no control); its words are for
    // the eye, the data table reads them.
    const mk = (name, attrs) => set(document.createElementNS('http://www.w3.org/2000/svg', name), name === 'text' ? { 'aria-hidden': 'true', ...attrs } : attrs);

    const KEYS = ['llama-32-1b', 'gpt-4-1-nano', 'gpt-4o-mini', 'gemini-15-flash', 'gemini-20-flash', 'llama-33-70b', 'claude-37-sonnet', 'gpt-4o', 'gemini-15-pro', 'deepseek-r1'];
    const SHORT = { 'llama-32-1b': '1B', 'gpt-4-1-nano': 'nano', 'gpt-4o-mini': '4o-mini', 'gemini-15-flash': '1.5 Flash', 'gemini-20-flash': '2.0 Flash', 'llama-33-70b': '70B', 'claude-37-sonnet': 'Sonnet', 'gpt-4o': 'GPT-4o', 'gemini-15-pro': '1.5 Pro', 'deepseek-r1': 'R1' };
    const models = KEYS.filter(k => DATA.MODELS[k]).map(k => {
        const m = DATA.MODELS[k], wh = m.energyPer1kTokens_Wh;
        return { key: k, label: m.label, short: SHORT[k] || m.label, wh, range: m.range || [wh, wh] };
    });
    const n = models.length;
    if (n < 5) return;
    const KNOWN = 3;

    // Drawn 640 units wide and scaled to fit, its labels were 5px tall on a
    // phone. It is as many units wide as the pixels it is shown in now (to
    // 640), so 11 units is 11px or more; under 480 it is taller (style.css
    // holds that shape), the model names steeper into the room below.
    const yMax = 1.6;
    let W, H, M, plotW, plotH, narrow;
    const xAt = (i) => M.l + (i / (n - 1)) * plotW;
    const yAt = (wh) => M.t + (1 - Math.min(wh, yMax) / yMax) * plotH;
    const whAtY = (y) => Math.max(0, Math.min(yMax, (1 - (y - M.t) / plotH) * yMax));
    const pts = (whs) => whs.map((wh, i) => `${xAt(i)},${yAt(wh)}`).join(' ');

    const guess = models.map((m, i) => (i < KNOWN ? m.wh : models[KNOWN - 1].wh));
    let revealed = false;
    let interacted = false;
    let cursor = KNOWN;

    // --- static layer: gridlines + y labels ---
    const grid = [0, 0.5, 1.0, 1.5].map(v => {
        const t = mk('text', { class: 'ydi-axis-label', 'text-anchor': 'end' });
        t.textContent = v.toFixed(1);
        return [v, svg.appendChild(mk('line', { class: 'ydi-grid' })), svg.appendChild(t)];
    });
    const yTitle = svg.appendChild(mk('text', { class: 'ydi-axis-title', 'text-anchor': 'start' }));
    yTitle.textContent = 'Wh / answer';

    // x labels
    const xLabels = models.map((m, i) => {
        const t = svg.appendChild(mk('text', { class: 'ydi-xlabel' + (i < KNOWN ? ' known' : ''), 'text-anchor': 'end' }));
        t.textContent = m.short;
        return t;
    });

    // divider + region labels
    const divider = svg.appendChild(mk('line', { class: 'ydi-divider' }));
    const pLabel = svg.appendChild(mk('text', { class: 'ydi-region-label predict', 'text-anchor': 'end' }));
    pLabel.textContent = 'you predict →';

    // known line + dots
    const knownLine = svg.appendChild(mk('polyline', { class: 'ydi-known-line' }));
    const knownDots = models.slice(0, KNOWN).map(() => svg.appendChild(mk('circle', { r: 4, class: 'ydi-known-dot' })));

    // the illustrative straight-line guess + the published estimates (both
    // revealed later, when the dots and the callout join them)
    const intuitLine = svg.appendChild(mk('polyline', { class: 'ydi-intuit-line' }));
    const realLine = svg.appendChild(mk('polyline', { class: 'ydi-real-line' }));
    const realDots = models.map(() => mk('circle', { r: 4, class: 'ydi-real-dot' }));
    const callout = mk('text', { class: 'ydi-callout', 'text-anchor': 'end' });

    // guess line + draggable dots
    const guessLine = svg.appendChild(mk('polyline', { class: 'ydi-guess-line' }));
    const guessDots = models.map((m, i) => (i < KNOWN ? null : svg.appendChild(mk('circle', { r: 5, class: 'ydi-guess-dot' }))));

    const drawGuess = () => {
        guessLine.setAttribute('points', pts(guess).split(' ').slice(KNOWN - 1).join(' '));
        for (let i = KNOWN; i < n; i++) set(guessDots[i], { cx: xAt(i), cy: yAt(guess[i]) });
        const g = guess[cursor].toFixed(2);
        set(hit, { 'aria-valuenow': g, 'aria-valuetext': `${models[cursor].short}: your guess ${g} Wh per answer` });
    };
    // Pulse the first predict dot so people know the curve is grabbable.
    if (guessDots[KNOWN]) guessDots[KNOWN].classList.add('ydi-dot-pulse');
    // Device-aware hint: touch users tap or drag; pointer users drag.
    const coarse = typeof window.matchMedia === 'function' && window.matchMedia('(pointer: coarse)').matches;
    if (hintEl && coarse) hintEl.textContent = 'tap or drag across to draw';

    // --- interaction (pointer + keyboard) ---
    const cursorRing = svg.appendChild(mk('circle', { class: 'ydi-cursor', r: 9 }));
    // A slider, its value the guess at the cursor, spoken as it changes
    // (role=application allows no value: each arrow press was silent).
    const hit = svg.appendChild(mk('rect', { class: 'ydi-hit', fill: 'transparent', tabindex: 0, role: 'slider', 'aria-valuemin': 0, 'aria-valuemax': yMax,
        'aria-label': 'Draw your prediction: left/right arrows move between models, up/down arrows (or Page Up/Down, Home, End) raise or lower the guessed energy, Enter reveals the research estimates. The Reveal button and the data table below are equivalent.' }));

    // The published estimates, and a third line: a straight-line guess that
    // misses the reasoning spike, drawn, not sourced, so the legend and the
    // data table say illustrative.
    const drawReveal = () => {
        const tiny = models[0].wh;
        realLine.setAttribute('points', pts(models.map(m => m.wh)));
        realDots.forEach((c, i) => set(c, { cx: xAt(i), cy: yAt(models[i].wh) }));
        intuitLine.setAttribute('points', pts(models.map((m, i) => tiny + (i / (n - 1)) * (0.55 - tiny))));
        set(callout, { x: xAt(n - 1) - 8, y: yAt(models[n - 1].wh) - 12 });
    };

    const place = () => {
        W = Math.min(640, placedAt) || 640;   // placedAt is 0 before layout (and in jsdom)
        narrow = W < 480;
        H = Math.round(narrow ? W * 0.8 : W * 380 / 640);
        M = narrow ? { l: 36, r: 12, t: 30, b: 64 } : { l: 58, r: 18, t: 26, b: 86 };
        plotW = W - M.l - M.r;
        plotH = H - M.t - M.b;
        svg.setAttribute('viewBox', `0 0 ${W} ${H}`);
        const lift = narrow ? 14 : 10;
        const ly = H - M.b + (narrow ? 14 : 20);
        grid.forEach(([v, line, t]) => {
            set(line, { x1: M.l, y1: yAt(v), x2: W - M.r, y2: yAt(v) });
            set(t, { x: M.l - (narrow ? 6 : 10), y: yAt(v) + 4 });
        });
        set(yTitle, { x: narrow ? 4 : M.l - 46, y: M.t - lift });
        xLabels.forEach((t, i) => set(t, { x: xAt(i), y: ly, transform: `rotate(${narrow ? -45 : -40} ${xAt(i)} ${ly})` }));
        const dividerX = (xAt(KNOWN - 1) + xAt(KNOWN)) / 2;
        set(divider, { x1: dividerX, y1: M.t, x2: dividerX, y2: M.t + plotH });
        set(pLabel, { x: xAt(n - 1), y: M.t - lift });
        knownLine.setAttribute('points', pts(models.slice(0, KNOWN).map(m => m.wh)));
        knownDots.forEach((c, i) => set(c, { cx: xAt(i), cy: yAt(models[i].wh) }));
        set(hit, { x: M.l, y: M.t, width: plotW, height: plotH });
        set(cursorRing, { cx: xAt(cursor), cy: yAt(guess[cursor]) });
        drawGuess();
        if (revealed) {
            // A new length for the line: its draw-in dashes go.
            realLine.style.strokeDasharray = realLine.style.strokeDashoffset = '';
            drawReveal();
        }
    };
    let placedAt;
    const fit = () => {
        const w = Math.round(svg.getBoundingClientRect().width);
        if (w !== placedAt) { placedAt = w; place(); }
    };
    fit();
    if ('ResizeObserver' in window) new ResizeObserver(fit).observe(svg);

    const markInteracted = () => {
        if (interacted) return;
        interacted = true;
        if (hintEl) hintEl.style.opacity = '0';
        if (guessDots[KNOWN]) guessDots[KNOWN].classList.remove('ydi-dot-pulse');
    };
    const toLocal = (evt) => {
        const rect = svg.getBoundingClientRect();
        return { x: (evt.clientX - rect.left) / rect.width * W, y: (evt.clientY - rect.top) / rect.height * H };
    };
    const paint = (p) => {
        if (revealed) return;
        let i = Math.round((p.x - M.l) / plotW * (n - 1));
        i = Math.max(KNOWN, Math.min(n - 1, i));
        guess[i] = whAtY(p.y);
        cursor = i;
        drawGuess();
        markInteracted();
    };
    let dragging = false;
    hit.addEventListener('pointerdown', (e) => {
        dragging = true;
        if (hit.setPointerCapture) { try { hit.setPointerCapture(e.pointerId); } catch (x) { /* ignore */ } }
        paint(toLocal(e));
        e.preventDefault();
    });
    hit.addEventListener('pointermove', (e) => { if (dragging) { paint(toLocal(e)); e.preventDefault(); } });
    window.addEventListener('pointerup', () => { dragging = false; });
    window.addEventListener('pointercancel', () => { dragging = false; });

    const moveCursor = () => set(cursorRing, { cx: xAt(cursor), cy: yAt(guess[cursor]) });
    hit.addEventListener('focus', () => { svg.classList.add('ydi-kbd'); moveCursor(); });
    hit.addEventListener('blur', () => { svg.classList.remove('ydi-kbd'); });
    // Every key a slider promises: Home, End and Page keys scrolled the page.
    hit.addEventListener('keydown', (e) => {
        if (revealed) return;
        const k = e.key;
        const step = yMax / (/^Page/.test(k) ? 6 : 24);
        if (k === 'ArrowLeft') cursor = Math.max(KNOWN, cursor - 1);
        else if (k === 'ArrowRight') cursor = Math.min(n - 1, cursor + 1);
        else if (k === 'ArrowUp' || k === 'PageUp') guess[cursor] = Math.min(yMax, guess[cursor] + step);
        else if (k === 'ArrowDown' || k === 'PageDown') guess[cursor] = Math.max(0, guess[cursor] - step);
        else if (k === 'Home' || k === 'End') guess[cursor] = k === 'End' ? yMax : 0;
        else if (k === 'Enter' || k === ' ') { doReveal(); e.preventDefault(); return; }
        else return;
        e.preventDefault();
        markInteracted();
        drawGuess();
        moveCursor();
    });

    // --- reveal ---
    const nudge = () => {
        if (hintEl) {
            hintEl.style.opacity = '';
            hintEl.classList.add('ydi-hint-nudge');
            setTimeout(() => hintEl.classList.remove('ydi-hint-nudge'), 1200);
        }
        if (guessDots[KNOWN]) guessDots[KNOWN].classList.add('ydi-dot-pulse');
    };

    const doReveal = () => {
        if (revealed) return;
        if (!interacted) { nudge(); return; }   // draw first — don't grade a guess never made
        revealed = true;
        const reduce = !window.mks.motionOK();
        drawReveal();
        svg.classList.add('revealed');
        // Draw the published estimates in, left to right.
        if (!reduce && realLine.getTotalLength) {
            const len = realLine.getTotalLength();
            realLine.style.strokeDasharray = String(len);
            realLine.style.strokeDashoffset = String(len);
            realLine.getBoundingClientRect(); // force reflow before transitioning
            realLine.style.transition = 'stroke-dashoffset 0.85s ease';
            realLine.style.strokeDashoffset = '0';
        }
        realDots.forEach(c => svg.appendChild(c));
        if (hintEl) hintEl.style.opacity = '0';
        if (resetBtn) resetBtn.hidden = false;
        if (shareBtn) shareBtn.hidden = false;
        // Reveal goes, and focus with it to the page, where a screen reader
        // says nothing of where it went: hand it to what takes its place.
        const next = shareBtn || resetBtn;
        if (next && document.activeElement === revealBtn) next.focus();
        revealBtn.hidden = true;

        // Each figure is a published estimate with a range, good to an order
        // of magnitude. A guess inside the range is not wrong, and a gap
        // quoted to a decimal against the central value was false precision.
        const gWh = Math.max(guess[n - 1], 0);
        const rWh = models[n - 1].wh;
        const tiny = models[0].wh;
        const [lo, hi] = models[n - 1].range, [tLo, tHi] = models[0].range;
        const factorFrontier = Math.round(rWh / tiny);
        const factors = `${Math.round(lo / tHi)}–${Math.round(hi / tLo).toLocaleString('en')}×`;
        const est = `The published estimate is about ${rWh} Wh (${lo}–${hi} Wh)`;
        let msg;
        if (gWh < 0.02) msg = `You put the biggest model near zero. ${est}: a dramatic underestimate of the frontier.`;
        else if (gWh < lo) msg = `You put the biggest model at ~${gWh.toFixed(2)} Wh. ${est}, so you underestimated the frontier, about ${Math.round(rWh / gWh)}× below its central figure.`;
        else if (gWh > hi) msg = `You had the frontier at ~${gWh.toFixed(2)} Wh. ${est}, so that is an overestimate.`;
        else msg = `You had the frontier at ~${gWh.toFixed(2)} Wh. ${est}: your guess is within that range.`;
        msg += ` A 1B model answers for about ${tiny} Wh, so the frontier reasoning model uses roughly ${factorFrontier}× more for the same 1,000-token answer (${factors} across the ranges). That gap is exactly what the tools people prompt with never show them.`;
        // Shape grade: did they capture the frontier spike, not just a magnitude?
        let guessPeak = KNOWN;
        for (let i = KNOWN + 1; i < n; i++) if (guess[i] > guess[guessPeak]) guessPeak = i;
        const spread = guess[n - 1] - guess[KNOWN];
        let shape;
        if (guessPeak === n - 1 && gWh >= lo) shape = 'You nailed the shape — you saw the frontier spike.';
        else if (guessPeak === n - 1) shape = 'You saw the spike, but under-scaled how steep it gets.';
        else if (spread < 0.1) shape = 'You drew it nearly flat — the research estimates hide a cliff at the frontier.';
        else shape = 'You put the peak before the frontier — the reasoning model is the outlier.';
        if (verdictEl) { verdictEl.innerHTML = `<span class="ydi-shape">${shape}</span> ${msg}`; verdictEl.hidden = false; }
        cardData = { shape, factor: factorFrontier, factors };
        // Callout on the frontier spike, where drawReveal put it.
        callout.textContent = `R1 · ~${factorFrontier}× a 1B model`;
        svg.appendChild(callout);
        if (legendEl) legendEl.hidden = false;
    };
    revealBtn.addEventListener('click', doReveal);

    // Shareable result card (dark, on-brand) — reuses the canvas-PNG pattern.
    const wrapText = (ctx, text, maxWidth) => {
        const words = text.split(' ');
        const out = [];
        let line = '';
        words.forEach(w => {
            const test = line ? line + ' ' + w : w;
            if (ctx.measureText(test).width > maxWidth && line) { out.push(line); line = w; }
            else line = test;
        });
        if (line) out.push(line);
        return out;
    };
    const drawCard = () => {
        if (!cardCanvas || !cardCanvas.getContext || !cardData) return;
        const scale = 2, W = 460, padX = 32, cw = W - padX * 2;
        let ctx = cardCanvas.getContext('2d');
        if (!ctx) return;
        ctx.font = "600 19px 'Space Grotesk', system-ui, sans-serif";
        const shapeLines = wrapText(ctx, cardData.shape, cw);
        ctx.font = "400 16px 'Inter', system-ui, sans-serif";
        const factorText = `By the published estimates, the frontier reasoning model uses about ${cardData.factor}× the energy per answer of a 1-billion-parameter model (${cardData.factors} across their ranges).`;
        const factorLines = wrapText(ctx, factorText, cw);
        const headerH = 78;
        const H = headerH + 26 + shapeLines.length * 26 + 14 + factorLines.length * 23 + 66;
        cardCanvas.width = W * scale; cardCanvas.height = H * scale;
        ctx = cardCanvas.getContext('2d');
        ctx.scale(scale, scale);
        ctx.fillStyle = '#0b1705'; ctx.fillRect(0, 0, W, H);
        ctx.textAlign = 'left'; ctx.textBaseline = 'alphabetic';
        ctx.fillStyle = '#7CFC00'; ctx.font = "700 24px 'Space Grotesk', system-ui, sans-serif";
        ctx.fillText("AI's Hidden Curve", padX, 40);
        ctx.fillStyle = '#9fdf7a'; ctx.font = "400 13px 'IBM Plex Mono', monospace";
        ctx.fillText('I guessed what one AI answer costs', padX, 62);
        let y = headerH + 22;
        ctx.fillStyle = '#eaffe0'; ctx.font = "600 19px 'Space Grotesk', system-ui, sans-serif";
        shapeLines.forEach(l => { ctx.fillText(l, padX, y); y += 26; });
        y += 12;
        ctx.fillStyle = '#cfe8c0'; ctx.font = "400 16px 'Inter', system-ui, sans-serif";
        factorLines.forEach(l => { ctx.fillText(l, padX, y); y += 23; });
        y += 24;
        ctx.fillStyle = '#7CFC00'; ctx.font = "600 15px 'Space Grotesk', system-ui, sans-serif";
        ctx.fillText('Moses Kolleh Sesay', padX, y);
        ctx.fillStyle = '#88a878'; ctx.font = "400 12px 'IBM Plex Mono', monospace";
        ctx.fillText(window.mks.share ? window.mks.share.site : 'moseskolleh.github.io/sustaintheworld', padX, y + 18);
    };
    if (shareBtn && cardCanvas) {
        shareBtn.addEventListener('click', () => {
            drawCard();
            const text = `${cardData ? cardData.shape : ''} I tried to guess what one AI answer costs. ${window.mks.share ? window.mks.share.site : ''}`;
            if (window.mks.share) window.mks.share.image(cardCanvas, 'ai-hidden-curve.png', text);
        });
    }

    if (resetBtn) {
        resetBtn.addEventListener('click', () => {
            revealed = false;
            svg.classList.remove('revealed');   // which hides the two lines
            realLine.style.cssText = '';
            if (legendEl) legendEl.hidden = true;
            realDots.forEach(d => d.remove());
            callout.remove();
            for (let i = KNOWN; i < n; i++) guess[i] = models[KNOWN - 1].wh;
            drawGuess();
            if (verdictEl) { verdictEl.hidden = true; verdictEl.textContent = ''; }
            revealBtn.hidden = false;
            if (document.activeElement === resetBtn) revealBtn.focus();
            resetBtn.hidden = true;
            if (shareBtn) shareBtn.hidden = true;
            interacted = false;
            if (hintEl) hintEl.style.opacity = '';
            if (guessDots[KNOWN]) guessDots[KNOWN].classList.add('ydi-dot-pulse');
        });
    }

    // --- accessible, non-visual data table ---
    if (tableEl) {
        const rows = models.map(m => `<tr><td>${m.label}</td><td>${m.wh} Wh</td></tr>`).join('');
        tableEl.innerHTML = `<table><caption>Estimated energy per 1,000-token answer by model: published estimates, to an order of magnitude, before data-centre overhead. The chart's straight-line guess is illustrative — from no source — so it is not listed here.</caption><thead><tr><th>Model</th><th>Wh per answer</th></tr></thead><tbody>${rows}</tbody></table>`;
    }
})();


// ===================================
// THE RECEIPT — this page prints its own itemised carbon bill
// Reads the same Resource Timing data as the footer badge, groups it by asset
// class, and renders a thermal-receipt you can save as a PNG. Pure vanilla:
// the PNG is drawn on a <canvas>, no library, no gigabyte of anything.
// ===================================
(() => {
    const btn = document.getElementById('receiptBtn');
    const panel = document.getElementById('receiptPanel');
    const body = document.getElementById('receiptBody');
    const dlBtn = document.getElementById('receiptDownload');
    const canvas = document.getElementById('receiptCanvas');
    if (!btn || !panel || !body) return;

    // The footer badge (script.js) defines what a byte weighs and how a
    // resource is measured; the receipt uses the same definitions rather than
    // carrying a copy that could drift.
    const carbon = window.mks.carbon;
    if (!carbon) return;
    const G_CO2_PER_MB = carbon.gramsPerMB;
    const MEDIAN_MB = carbon.medianPageMB;
    const bytesOf = carbon.bytesOf;
    const pageOrigin = location.origin;
    const urlText = (location.hostname + location.pathname).replace(/\/+$/, '') || 'moseskolleh.github.io/sustaintheworld';
    let lastReceiptG = 0;

    const classify = (r) => {
        const t = r.initiatorType;
        const n = (r.name || '').toLowerCase();
        if (/\.(woff2?|ttf|otf|eot)(\?|$)/.test(n)) return 'Fonts';
        if (t === 'img' || /\.(webp|png|jpe?g|gif|svg|avif)(\?|$)/.test(n)) return 'Images';
        if (t === 'script' || /\.js(\?|$)/.test(n)) return 'Scripts';
        if (t === 'link' || t === 'css' || /\.css(\?|$)/.test(n)) return 'Styles';
        return 'Other';
    };

    const ORDER = ['HTML', 'Styles', 'Scripts', 'Fonts', 'Images', 'Other'];

    const gather = () => {
        const g = { HTML: 0, Styles: 0, Scripts: 0, Fonts: 0, Images: 0, Other: 0 };
        let unmeasured = 0;
        try {
            const nav = performance.getEntriesByType('navigation')[0];
            if (nav) g.HTML += bytesOf(nav);
            performance.getEntriesByType('resource').forEach(r => {
                const b = bytesOf(r);
                if (b === 0) {
                    if (r.name && r.name.indexOf(pageOrigin) !== 0) unmeasured++;
                    return;
                }
                g[classify(r)] += b;
            });
        } catch (e) { /* older browsers: receipt stays empty */ }
        return { g, unmeasured };
    };

    const fmtSize = (b) => (b >= 1048576 ? (b / 1048576).toFixed(2) + ' MB' : Math.round(b / 1024) + ' KB');
    const fmtG = (grams) => (grams >= 1 ? grams.toFixed(2) : grams.toFixed(3)) + ' g';

    const buildLines = () => {
        const { g, unmeasured } = gather();
        let total = 0;
        ORDER.forEach(k => { total += g[k]; });
        const totalMb = total / 1048576;
        const totalG = totalMb * G_CO2_PER_MB;
        lastReceiptG = totalG;
        const dt = new Date();
        const pad = (n) => String(n).padStart(2, '0');
        const stamp = `${dt.getFullYear()}-${pad(dt.getMonth() + 1)}-${pad(dt.getDate())}  ${pad(dt.getHours())}:${pad(dt.getMinutes())}`;

        const lines = [];
        lines.push({ t: 'c', s: 'MKS · SUSTAINTHEWORLD', b: true });
        lines.push({ t: 'c', s: 'page-load carbon receipt' });
        lines.push({ t: 'c', s: stamp, dim: true });
        lines.push({ t: 'd' });
        ORDER.forEach(k => {
            if (g[k] > 0) {
                const grams = (g[k] / 1048576) * G_CO2_PER_MB;
                lines.push({ t: 'r', l: k, r: `${fmtSize(g[k])}   ${fmtG(grams)}` });
            }
        });
        lines.push({ t: 'd' });
        lines.push({ t: 'r', l: 'TOTAL', r: `${fmtSize(total)}   ${fmtG(totalG)}`, b: true });
        lines.push({ t: 'c', s: 'CO₂e · global avg grid', dim: true });
        lines.push({ t: 'd' });
        lines.push({ t: 'r', l: 'Median web page', r: `${MEDIAN_MB.toFixed(2)} MB` });
        if (totalMb < MEDIAN_MB) {
            lines.push({ t: 'c', s: `— you're ${Math.round((1 - totalMb / MEDIAN_MB) * 100)}% lighter —` });
        }
        lines.push({ t: 'r', l: 'Text-only report', r: '9 KB' });
        if (unmeasured) {
            lines.push({ t: 'c', s: `* ${unmeasured} off-site request${unmeasured > 1 ? 's' : ''} not counted`, dim: true });
        }
        lines.push({ t: 'd' });
        lines.push({ t: 'c', s: 'browsed lightly — say hello' });
        lines.push({ t: 'd' });
        lines.push({ t: 'c', s: 'MOSES KOLLEH SESAY', b: true });
        lines.push({ t: 'c', s: urlText, dim: true });
        lines.push({ t: 'c', s: 'climate · ESG · sustainable AI' });
        lines.push({ t: 'c', s: '||‖|‖||‖|||‖|‖||‖|||', mono: true });
        return lines;
    };

    const renderDOM = (lines) => {
        body.innerHTML = '';
        lines.forEach(ln => {
            let el;
            if (ln.t === 'd') {
                el = document.createElement('div');
                el.className = 'receipt-divider';
            } else if (ln.t === 'c') {
                el = document.createElement('div');
                el.className = 'receipt-center' + (ln.b ? ' receipt-strong' : '') + (ln.dim ? ' receipt-dim' : '') + (ln.mono ? ' receipt-barcode' : '');
                el.textContent = ln.s;
            } else {
                el = document.createElement('div');
                el.className = 'receipt-row' + (ln.b ? ' receipt-strong' : '');
                const l = document.createElement('span'); l.textContent = ln.l;
                const r = document.createElement('span'); r.textContent = ln.r;
                el.appendChild(l); el.appendChild(r);
            }
            body.appendChild(el);
        });
    };

    const drawCanvas = (lines) => {
        if (!canvas || !canvas.getContext) return;
        const scale = 2, W = 340, padX = 22, padY = 22, lh = 22;
        const H = padY * 2 + lines.length * lh;
        canvas.width = W * scale;
        canvas.height = H * scale;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;
        ctx.scale(scale, scale);
        ctx.fillStyle = '#f5f3ea';
        ctx.fillRect(0, 0, W, H);
        ctx.textBaseline = 'middle';
        let y = padY + lh / 2;
        lines.forEach(ln => {
            ctx.fillStyle = ln.dim ? '#6b665a' : '#1a1a1a';
            ctx.font = `${ln.b ? '700' : '400'} 13px 'IBM Plex Mono', ui-monospace, monospace`;
            if (ln.t === 'd') {
                ctx.strokeStyle = '#b7b1a1';
                ctx.setLineDash([2, 3]);
                ctx.beginPath(); ctx.moveTo(padX, y); ctx.lineTo(W - padX, y); ctx.stroke();
                ctx.setLineDash([]);
            } else if (ln.t === 'c') {
                ctx.textAlign = 'center';
                ctx.fillText(ln.s, W / 2, y);
            } else {
                ctx.textAlign = 'left';
                ctx.fillText(ln.l, padX, y);
                ctx.textAlign = 'right';
                ctx.fillText(ln.r, W - padX, y);
            }
            y += lh;
        });
    };

    let built = false;
    const build = () => {
        const lines = buildLines();
        renderDOM(lines);
        drawCanvas(lines);
        built = true;
    };

    btn.addEventListener('click', () => {
        const open = panel.hasAttribute('hidden');
        if (open) build();
        panel.toggleAttribute('hidden', !open);
        btn.setAttribute('aria-expanded', String(open));
        if (open) panel.scrollIntoView({ behavior: window.mks.scrollMotion(), block: 'nearest' });
    });

    if (dlBtn && canvas) {
        dlBtn.addEventListener('click', () => {
            if (!built) build();
            const fn = 'carbon-receipt-' + lastReceiptG.toFixed(3).replace('.', '_') + 'g.png';
            if (!window.mks.share) return;
            const msg = `This whole climate portfolio cost ${lastReceiptG.toFixed(2)} g CO₂e to view — ${window.mks.share.site}`;
            window.mks.share.image(canvas, fn, msg);
        });
    }
})();

// Tells the loader in script.js that this module is in place.
window.mks.loaded.interactives = true;
