// ===================================================================
// GENERATED by scripts/build-content.js from content/narration.json.
// Do not edit this file — your changes will be overwritten.
// Edit content/narration.json, then run: npm run build:content
// How the scripts are written, and why, is the $comment at its top: it
// stays there rather than in every visitor's download.
// ===================================================================
(function (root, factory) {
    const data = factory();
    root.VoiceScripts = data;
    if (typeof module !== 'undefined' && module.exports) module.exports = data;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
    // `id` is the section's element id (the hero's is #home), and the
    // file name if anyone opts in to rendering it: assets/audio/<id>.mp3
    // `label` is how the player names that section.
    const SCRIPTS = [
        {
            id: "hero",
            label: "the introduction",
            text: "Kushe. I'm Moses Kolleh Sesay — a sustainability and climate analyst based in Amsterdam. Geologist by training, sustainability analyst by conviction. I've drilled for water in Sierra Leone, modelled river pollution for the world's coasts, supported the United Nations' disaster-risk work, and now I'm teaching AI to tread lightly on the planet. A hundred and sixty-four water points delivered. Fifty-four hazard systems documented. Three continents, two master's degrees, one thread running through all of it. You can read this page, or you can let me walk you through it. Either way — welcome."
        },
        {
            id: "journey",
            label: "the journey",
            text: "Four countries, three continents, one thread: water, climate, and the data that connects them. It starts in Freetown, Sierra Leone. Between twenty-thirteen and twenty-nineteen I graduated top of my class in geology, then took it straight to the field — leading drilling crews that delivered a hundred and sixty-four water points across the country. Then Changsha, China, on a full Chinese Government scholarship, for a master's in industrial engineering. My thesis asked how we might manage water beyond cement, steel and pipes. Then Bonn, Germany, and climate adaptation work at the U.N. Office for Disaster Risk Reduction, where I documented fifty-four global hazard information systems. Then Wageningen, in the Netherlands, for a master's in environmental sciences. And now Amsterdam, where the thread runs into sustainable A.I. Scroll, and the map flies the route with you."
        },
        {
            id: "about",
            label: "the about section and field notes",
            text: "I grew up where water scarcity isn't a statistic — it's a morning routine. That's why everything I do starts from the same question: how do we make environmental decisions that actually hold up in the real world? I hold two master's degrees — environmental sciences from Wageningen, and industrial engineering from Hunan. That puts me at the intersection of field experience and analytical rigour. I've managed water projects that delivered a hundred and sixty-four water points, reviewed disaster-loss data for the United Nations, and built climate-risk and E.S.G. analyses that decision-makers can actually act on. Today my focus is sustainable A.I. — making sure the tools we use to solve the climate crisis don't quietly become part of it. Then three field notes: short dispatches from the intersection of mud, models and megawatts. The first is about what a hundred and sixty-four water points taught me about data. In the Freetown Complex, a wrong guess isn't a bad cell in a spreadsheet — it's a dry hole a community paid for. Geophysics taught me that data only matters when someone stakes something on it. The resistivity surveys behind our groundwater maps pushed the strike rate to seventy percent, in rock where drilling is otherwise a gamble. And every strike carried the same lesson: collect the data before the drill bit, not after. I carry that into every E.S.G. analysis and every A.I. framework I build now. The question is never \"what does the data say?\" It's \"who is about to spend money, or drink water, based on what I claim it says?\""
        },
        {
            id: "experience",
            label: "the experience log",
            text: "I've logged my career the way a geologist logs a borehole: depth is time, and every layer is a chapter. At the surface, as last logged, I'm a researcher in sustainable artificial intelligence at the Digital Society School, part of the Amsterdam University of Applied Sciences, working in partnership with the Dutch Ministry of Finance. I'm building a framework and a working prototype that weigh the benefits of generative A.I. against its environmental costs — mapping the electricity, the hardware, and the data-centre water behind A.I. workloads, and setting that against European sustainability disclosure logic. Below that layer sit the earlier chapters: the OnePointFive sustainability consulting accelerator, the United Nations in Bonn, and underneath it all, the drilling crews in Sierra Leone. Press More on any layer to read it in full."
        },
        {
            id: "projects",
            label: "the projects",
            text: "Six projects, each with its headline result and how I know it. One, the sustainable A.I. framework: a working decision-support prototype, not a slide deck. You can check that: the team's prototypes are public on GitHub, as Sustainable A.I. Prototypes, with my role in its README. Two, coastal water pollution dynamics: ten thousand two hundred and twenty-six sub-basins modelled. You can check that too: it is a property of the model domain used, not an estimate. Three, a flood-resilient Wuppertal: a complete flood-risk management framework, delivered to the municipality. You cannot check that from outside: the client holds the deliverable, and nothing here claims it was implemented. Four, disaster risk reduction with the United Nations in Bonn: fifty-four global hazard information systems, identified and documented. You cannot check that either: it is a count recorded in the deliverable, which the United Nations office holds. Five, soft path water management: successfully defended at Hunan University, in May twenty twenty-one. You can check that: the degree was awarded, a master's in industrial engineering. And six, groundwater potential mapping: a seventy per cent aquifer strike rate in the drilling that followed. You cannot check that either: it comes from the field records of the boreholes sited with the survey, not a controlled trial. The whole of each is in the case studies, and two of them you can play with there: site a borehole, or flood a river."
        },
        {
            id: "ecoprompt",
            label: "the A.I. energy chart",
            text: "This is one question from my current research: how much energy does a single A.I. answer take as the models get bigger? Have a guess. The three smallest models are already plotted for you. Drag across the chart to predict the rest, from mid-size models up to a frontier reasoning model — then reveal what the research estimates. A straight line is the natural guess. It isn't one. The gap between that guess and what the research estimates is, more or less, my entire job. The full calculator, and where one answer lands on a sustainability report, are on their own page: the EcoPrompt Coach."
        },
        {
            id: "skills",
            label: "the skills and education section",
            text: "No made-up percentages here. Every tool comes with the receipt of where it earned its place. Python — for a groundwater toolkit, on GitHub. Q.G.I.S. and Arc.G.I.S. — for groundwater maps that struck water seven times out of ten; the maps are on request, with no public G.I.S. project yet. S.Q.L. — in an A-B test on GitHub, with a statistics notebook. Tableau — a dashboard linked from that test. Machine learning, from the Google Advanced Data Analytics certificate; no public project yet. And JavaScript — which built the EcoPrompt Coach, on GitHub. Alongside those: E.S.G. analysis, greenhouse gas accounting across scopes one to three, climate risk assessment, and water resource management. Each tool links to where it earned its place, or says there is no public project yet. Click through and check. Then three degrees, on three continents. A master's in environmental sciences from Wageningen University in the Netherlands, from twenty twenty-one to twenty twenty-four, specialising in human-environment interaction and water systems under global change. My thesis examined the socioeconomic drivers of river export of pollutants worldwide. I studied there as a Wageningen African Scholarship Programme scholar. Before that, a master's in industrial engineering from Hunan University in Changsha, China, on a full Chinese Government scholarship, with a thesis on soft path water management using Freetown as the case study. And underneath both, where it began: a bachelor's with honours in geology from the University of Sierra Leone. First class honours, top of the class, with a dissertation on groundwater potential mapping. Since then, four certificates: the Corporate Finance Institute's E.S.G. Specialist Program, Google's Advanced Data Analytics, data analytics training at Masterschool, and the U.N. System Staff College's course on disaster risk reduction and climate change adaptation."
        },
        {
            id: "contact",
            label: "the contact section",
            text: "I'm open to roles and consulting in sustainability, climate risk, E.S.G. and sustainable A.I. — in Amsterdam and the E.U., and remote-friendly. I usually reply within a couple of days. And if you're still deciding, there's a tool below the form. Open it, paste in a job description, and it grades how well my record fits the role, mapping each requirement to the evidence that backs it, and listing the ones this site can't show. It runs entirely in your browser. The text never leaves this page, and no A.I. model is downloaded to do it."
        }
    ];

    // The captions for Moses's recorded introduction, which he reads from
    // this text. Never spoken by the browser voice.
    const INTRO = {
        id: "intro",
        label: "Moses introduces himself",
        readBy: "Moses Kolleh Sesay",
        text: "Kushe. I'm Moses Kolleh Sesay, a sustainability and climate analyst based in Amsterdam. I trained as a geologist in Sierra Leone, where my dissertation mapped groundwater in the hard rock around Freetown. In the field, I worked on drilling projects that delivered a hundred and sixty-four water points, and reading the ground before drilling took our strike rate to seven holes in ten. That taught me the rule I still work by: collect the data before the drill bit, not after. Since then I have earned two master's degrees, in industrial engineering at Hunan University in China and in environmental sciences at Wageningen in the Netherlands. I modelled river pollution across more than ten thousand sub-basins, and at the United Nations in Bonn I documented fifty-four hazard information systems. Today I research sustainable A.I. at the Digital Society School in Amsterdam, with the Dutch Ministry of Finance, weighing what generative A.I. costs in electricity, hardware and water against what it gives back. Each of these has a case study on this site, with its evidence and its limits. If your work touches climate, water or A.I., I would like to hear from you."
    };

    // Sentence splitting, shared by the player (for utterances and captions)
    // and the generator, which says why it parks initialisms (A.I.) first.
    const INITIALISM = /[A-Za-z]+(?:\.[A-Za-z])+\./g;

    function splitSentences(text) {
        const parked = [];
        const masked = String(text).replace(INITIALISM, (m) => {
            parked.push(m);
            return `@@${parked.length - 1}@@`;
        });
        const restore = s => s.replace(/@@(\d+)@@/g, (_, i) => parked[Number(i)]);
        const raw = masked.match(/[^.!?…]+[.!?…]+["'”’—]?\s*/g) || [masked];

        // Fold very short fragments into the previous sentence — a two-word
        // utterance reads as a stutter and costs an extra engine round-trip.
        const out = [];
        raw.map(s => restore(s).trim()).filter(Boolean).forEach(s => {
            if (out.length && s.length < 40) out[out.length - 1] += ' ' + s;
            else out.push(s);
        });
        return out.length ? out : [String(text)];
    }

    const byId = {};
    SCRIPTS.forEach(s => { byId[s.id] = s; });

    return { SCRIPTS, byId, splitSentences, INTRO };
});
