#!/usr/bin/env node
// ===================================================================
// BUILD CONTENT — one source, every derived page
//
//     npm run build:content          write the generated files
//     npm run build:content -- --check   fail if any of them is out of date
//
// The site's facts used to live in six places at once: index.html, its
// JSON-LD block, field-report.html, the narration scripts, the README and the
// CV. Nothing kept them in step and they had already drifted. Everything this
// script writes is now derived from content/, and --check runs in CI so a
// hand-edit to a generated file cannot survive a push.
//
// GENERATED (do not hand-edit — the header on each file says so):
//
//   case-studies.html   problem → method → artifact → result, per project,
//                       with role lenses
//   research.html       research outputs and how to reproduce them
//   sitemap.xml         every page, with a lastmod that is not in the future
//   voice-scripts.js    the narration module, from content/narration.json
//   index.html          the JSON-LD block only, between its markers
//
// STILL HAND-AUTHORED: index.html and field-report.html. They are long-form
// editorial pages, and templating 130 KB of hand-tuned markup to remove
// duplication that a test already catches would trade a small problem for a
// large one. tests/content.test.js holds them to content/ instead.
//
// The output is deterministic — no dates, no ordering by filesystem, no
// randomness — because --check compares bytes.
// ===================================================================

const fs = require('fs');
const path = require('path');
const content = require('./lib/content.js');

const ROOT = content.ROOT;
const CHECK = process.argv.slice(2).includes('--check');

const GENERATED_BY = 'scripts/build-content.js';
const SITE = 'https://moseskolleh.github.io/sustaintheworld/';

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------
const esc = (s) => String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

// Typographic tidy-up for prose: the content files are written with plain
// ASCII quotes and dashes so they stay easy to edit and diff.
const prose = (s) => esc(s)
    .replace(/ — /g, ' &mdash; ')
    .replace(/(\d)-(\d)/g, '$1&ndash;$2');

const slug = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** Pulls named <symbol> definitions out of the sprite index.html already ships. */
function sprite(ids) {
    const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
    const symbols = ids.map((id) => {
        const m = html.match(new RegExp(`<symbol id="${id}"[\\s\\S]*?</symbol>`));
        if (!m) throw new Error(`icon #${id} is not in the index.html sprite`);
        return m[0];
    });
    return `<svg xmlns="http://www.w3.org/2000/svg" class="icon-sprite" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">${symbols.join('')}</svg>`;
}

const STATUS_LABEL = {
    'public': 'Public',
    'on-request': 'On request',
    'internal': 'Held by the client',
    'planned': 'Planned'
};

const STATUS_EXPLAIN = {
    'public': 'Open it now.',
    'on-request': 'It exists and I hold it — ask and I will send it.',
    'internal': 'Belongs to the organisation it was made for, not mine to publish.',
    'planned': 'Intended, not yet done.'
};

/** The availability chip shown next to every artifact and output. */
function statusChip(entry) {
    const label = STATUS_LABEL[entry.status] || entry.status;
    const explain = STATUS_EXPLAIN[entry.status] || '';
    const held = entry.heldBy ? ` ${entry.heldBy}.` : '';
    return `<span class="cs-status cs-status-${entry.status}" title="${esc(explain + held)}">${esc(label)}</span>`;
}

function pageShell({ title, description, canonical, heroTag, heroTitle, heroLead, main, bodyEnd = '', icons = ['i-arrow-right'] }) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- GENERATED by ${GENERATED_BY} from content/ — do not edit by hand.
         Edit the JSON under content/ and run: npm run build:content -->
    <title>${esc(title)}</title>
    <meta name="description" content="${esc(description)}">
    <meta name="author" content="Moses Kolleh Sesay">
    <link rel="canonical" href="${esc(canonical)}">
    <link rel="icon" type="image/svg+xml" href="assets/favicon.svg">
    <meta name="theme-color" content="#0a0a0a">
    <meta property="og:type" content="website">
    <meta property="og:title" content="${esc(title)}">
    <meta property="og:description" content="${esc(description)}">
    <meta property="og:url" content="${esc(canonical)}">
    <meta property="og:image" content="${SITE}assets/img/og-image.jpg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${esc(title)}">
    <meta name="twitter:description" content="${esc(description)}">
    <meta name="twitter:image" content="${SITE}assets/img/og-image.jpg">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&amp;family=Inter:wght@400;500;600&amp;family=IBM+Plex+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="carbon-ai.css">
    <link rel="stylesheet" href="content.css">
</head>
<body>
    ${sprite(icons)}
    <nav class="ca-nav" aria-label="Main">
        <a href="index.html" class="ca-nav-logo" aria-label="Back to portfolio home">
            <svg viewBox="0 0 40 40" aria-hidden="true">
                <circle cx="20" cy="20" r="17" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.35"/>
                <circle cx="20" cy="20" r="12" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.55"/>
                <circle cx="20" cy="20" r="7" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.8"/>
                <circle cx="20" cy="20" r="2.5" fill="currentColor"/>
            </svg>
            <span class="ca-nav-name">MK<span class="ca-accent">S</span></span>
        </a>
        <a href="index.html" class="ca-back"><svg class="icon icon-flip" aria-hidden="true" focusable="false"><use href="#i-arrow-right"></use></svg> Back to portfolio</a>
    </nav>
    <main class="ca-shell" id="main">
        <header class="ca-hero">
            <div class="ca-hero-tag">${esc(heroTag)}</div>
            <h1>${heroTitle}</h1>
            <p>${heroLead}</p>
        </header>
${main}
    </main>
${bodyEnd}
</body>
</html>
`;
}

// ------------------------------------------------------------------
// case-studies.html
// ------------------------------------------------------------------
/** The file a lens is served from. Static pages, not query strings — see below. */
function lensPage(lensId) {
    return lensId === 'all' ? 'case-studies.html' : `case-studies-${lensId}.html`;
}

// Each lens is its own fully-rendered static page.
//
// The first version of this shipped one page holding every lens panel, with
// `?lens=water` selected by JavaScript. On GitHub Pages the query string
// cannot change the bytes the server sends, so with scripting off — or
// blocked, or simply failing — following a lens link re-served the "Everything"
// framing in the original order while the README claimed the lens worked
// without JavaScript. That is precisely the kind of unenforced claim the rest
// of this work exists to remove, so the claim is now true by construction:
// there is no client-side lens logic left to fail.
//
// Four small pages cost less than one page carrying four hidden panels plus
// the script to switch them, and each view gets a real URL and canonical.
function renderCaseStudies(data, lens) {
    const { projects, lenses } = data;
    const all = [lenses.default].concat(lenses.lenses);

    const switcher = `
        <nav class="cs-lenses" aria-label="Portfolio views">
            <span class="cs-lenses-label mono-label">Viewing as</span>
            ${all.map(l => l.id === lens.id
                ? `<span class="cs-lens is-active" aria-current="page">${esc(l.shortLabel || l.label)}</span>`
                : `<a class="cs-lens" href="${lensPage(l.id)}">${esc(l.shortLabel || l.label)}</a>`
            ).join('\n            ')}
        </nav>`;

    const evidence = lens.evidence
        ? `<ul class="cs-lens-evidence">${lens.evidence.map(e => `<li>${prose(e)}</li>`).join('')}</ul>`
        : '';
    const bestFor = lens.bestFor ? `<p class="cs-lens-bestfor"><strong>Best fit for:</strong> ${prose(lens.bestFor)}</p>` : '';
    const panels = `
        <section class="cs-lens-panel" aria-labelledby="lens-${esc(lens.id)}-h">
            <h2 id="lens-${esc(lens.id)}-h">${esc(lens.label)}${lens.tagline ? ` <span class="cs-lens-tagline">${prose(lens.tagline)}</span>` : ''}</h2>
            <p class="cs-lens-summary">${prose(lens.summary)}</p>
            ${bestFor}
            ${evidence}
        </section>`;

    const card = (cs, secondary) => {
        const artifacts = cs.artifacts.map((a) => {
            const name = a.status === 'public' && a.url
                ? `<a href="${esc(a.url)}">${prose(a.name)}</a>`
                : prose(a.name);
            return `
                    <li class="cs-artifact">
                        <div class="cs-artifact-head">
                            <span class="cs-artifact-kind mono-label">${esc(a.kind || 'output')}</span>
                            ${statusChip(a)}
                        </div>
                        <div class="cs-artifact-name">${name}</div>
                        ${a.note ? `<p class="cs-artifact-note">${prose(a.note)}</p>` : ''}
                        ${a.heldBy ? `<p class="cs-artifact-note">Held by ${prose(a.heldBy)}.</p>` : ''}
                    </li>`;
        }).join('');

        const results = cs.results.map(r => `
                    <li class="cs-result${r.verifiable ? ' cs-result-verifiable' : ''}">
                        <p class="cs-result-claim">${prose(r.claim)}</p>
                        <p class="cs-result-basis"><span class="mono-label">How this is known</span> ${prose(r.basis)}</p>
                        <p class="cs-result-check">${r.verifiable
                            ? 'You can check this yourself.'
                            : 'You cannot check this from outside — it rests on records held elsewhere.'}</p>
                    </li>`).join('');

        return `
            <article class="cs-card${secondary ? ' cs-card-secondary' : ''}" id="${esc(cs.id)}" data-lenses="${esc((cs.lenses || []).join(' '))}">
                <header class="cs-card-head">
                    <p class="cs-card-meta mono-label">${esc(cs.period)} &middot; ${esc(cs.location)}</p>
                    <h3>${prose(cs.title)}</h3>
                    <p class="cs-card-sub">${prose(cs.subtitle || '')}</p>
                    <p class="cs-card-org">${prose(cs.organization)}${cs.partner ? ` &middot; with ${prose(cs.partner)}` : ''}${cs.role ? ` &middot; ${prose(cs.role)}` : ''}</p>
                </header>

                <div class="cs-stage">
                    <h4 class="cs-stage-h"><span class="cs-stage-n">01</span> Problem</h4>
                    <p>${prose(cs.problem)}</p>
                </div>

                <div class="cs-stage">
                    <h4 class="cs-stage-h"><span class="cs-stage-n">02</span> Method</h4>
                    <ul class="cs-method">${cs.method.map(m => `<li>${prose(m)}</li>`).join('')}</ul>
                </div>

                <div class="cs-stage">
                    <h4 class="cs-stage-h"><span class="cs-stage-n">03</span> Artifact</h4>
                    <ul class="cs-artifacts">${artifacts}
                    </ul>
                </div>

                <div class="cs-stage">
                    <h4 class="cs-stage-h"><span class="cs-stage-n">04</span> Result</h4>
                    <ul class="cs-results">${results}
                    </ul>
                </div>
${cs.caveat ? `
                <p class="cs-caveat"><span class="mono-label">Caveat</span> ${prose(cs.caveat)}</p>` : ''}
            </article>`;
    };

    // Matching case studies first, the rest below — reordered at build time,
    // so the order a visitor sees does not depend on scripting.
    const { primary, secondary } = content.orderForLens(projects.caseStudies, lens.id);
    const cards = primary.map(cs => card(cs, false))
        .concat(secondary.map(cs => card(cs, true)))
        .join('\n');

    const main = `${switcher}
${panels}

        <p class="cs-note">
            Every case study below is on this page in every view &mdash; a lens reorders and frames,
            it never hides. Each result says how it was measured, and whether you can check it
            from outside. Where the answer is no, it says so.
        </p>

        <div class="cs-grid" id="csGrid">
${cards}
        </div>

        <section class="cs-footnote">
            <h2>Why it is laid out like this</h2>
            <p>
                A portfolio that lists outcomes without saying how they were measured is asking to be
                taken on trust. Splitting each project into <strong>problem &rarr; method &rarr; artifact &rarr;
                result</strong> makes the weak link visible: a strong method with an internal-only artifact
                is a different thing from a public tool anyone can run, and both are different from a
                number with no baseline behind it.
            </p>
            <p>
                The content lives in <code>content/projects.json</code>. A test fails the build if any
                result loses its basis, if an artifact claims to be public without a working link, or if
                a link points somewhere this repository has not already vouched for.
            </p>
        </section>`;

    return pageShell({
        title: lens.id === 'all'
            ? 'Case studies — Moses Kolleh Sesay'
            : `Case studies: ${lens.label} — Moses Kolleh Sesay`,
        description: lens.id === 'all'
            ? 'Six projects in water, climate risk and sustainable AI — problem, method, artifact and measurable result, with the basis for every number.'
            : `${lens.label}: ${lens.summary.slice(0, 150)}`,
        canonical: `${SITE}${lensPage(lens.id)}`,
        heroTag: 'PROBLEM &middot; METHOD &middot; ARTIFACT &middot; RESULT',
        heroTitle: 'Case <span class="ca-accent">studies</span>',
        heroLead: 'Six projects across four countries, each one traced from the question that started it to what it actually produced &mdash; and to how far you can check the result from where you are sitting.',
        main
    });
}

// ------------------------------------------------------------------
// research.html
// ------------------------------------------------------------------
function renderResearch(data) {
    const { research } = data;

    const byType = {};
    research.outputs.forEach((o) => {
        (byType[o.type] = byType[o.type] || []).push(o);
    });

    const counts = content.STATUSES
        .map(s => ({ status: s, n: research.outputs.filter(o => o.status === s).length }))
        .filter(c => c.n);

    const summary = `
        <ul class="rs-summary">
            ${counts.map(c => `<li><strong>${c.n}</strong> ${esc(STATUS_LABEL[c.status].toLowerCase())}</li>`).join('')}
        </ul>`;

    const entry = (o) => {
        const title = o.status === 'public' && o.url
            ? `<a href="${esc(o.url)}">${prose(o.title)}</a>`
            : prose(o.title);
        return `
                <article class="rs-item" id="${esc(o.id)}">
                    <div class="rs-item-head">
                        <span class="rs-type mono-label">${esc(o.type)}</span>
                        <span class="rs-year mono-label">${esc(o.year)}</span>
                        ${statusChip(o)}
                    </div>
                    <h3>${title}</h3>
                    ${o.venue ? `<p class="rs-venue">${prose(o.venue)}</p>` : ''}
                    <p class="rs-summary-text">${prose(o.summary)}</p>
                    ${o.methods && o.methods.length
                        ? `<p class="rs-methods"><span class="mono-label">Methods</span> ${o.methods.map(prose).join(' &middot; ')}</p>`
                        : ''}
                    ${o.note ? `<p class="rs-note">${prose(o.note)}</p>` : ''}
                    ${o.heldBy ? `<p class="rs-note">Held by ${prose(o.heldBy)}.</p>` : ''}
                    ${o.caseStudy ? `<p class="rs-link"><a href="case-studies.html#${esc(o.caseStudy)}">Read the case study &rarr;</a></p>` : ''}
                </article>`;
    };

    const sections = Object.keys(byType).map(type => `
            <section class="rs-group">
                <h2>${esc(type)}${byType[type].length > 1 ? 's' : ''}</h2>
                ${byType[type].map(entry).join('\n')}
            </section>`).join('\n');

    const repro = research.reproducibility;
    const reproSection = `
        <section class="rs-repro">
            <h2>${esc(repro.heading)}</h2>
            <p>${prose(repro.body)}</p>
            <dl class="rs-commands">
                ${repro.commands.map(c => `<dt><code>${esc(c.command)}</code></dt><dd>${prose(c.does)}</dd>`).join('\n                ')}
            </dl>
        </section>`;

    const main = `
        <section class="rs-intro">
            <p>${prose(research.intro)}</p>
            ${summary}
            <p class="rs-key">
                <strong>Public</strong> means you can open it right now.
                <strong>On request</strong> means it exists and I hold it &mdash; ask.
                <strong>Held by the client</strong> means it belongs to the organisation it was made for.
                No entry on this page names a journal, a conference or a DOI, because none of this work has one.
            </p>
        </section>
${sections}
${reproSection}`;

    return pageShell({
        title: 'Research outputs — Moses Kolleh Sesay',
        description: 'Theses, reports, datasets, code and tools — what exists, where it is, and who holds the parts that are not public.',
        canonical: `${SITE}research.html`,
        heroTag: 'WHAT EXISTS &middot; WHERE IT IS &middot; WHO HOLDS IT',
        heroTitle: 'Research <span class="ca-accent">outputs</span>',
        heroLead: 'Three degrees of research, a consultancy, an internship and a working tool. Some of it is public, some belongs to the organisations it was done for, and the rest is a PDF I will happily send you.',
        main
    });
}

// ------------------------------------------------------------------
// sitemap.xml
// ------------------------------------------------------------------
function renderSitemap(data) {
    const pages = data.profile.pages;
    const entries = pages.map(p => `  <url>
    <loc>${esc(p.loc)}</loc>
    <lastmod>${esc(p.lastmod)}</lastmod>
    <changefreq>${esc(p.changefreq || 'monthly')}</changefreq>
    <priority>${esc(p.priority || '0.5')}</priority>
  </url>`).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by ${GENERATED_BY} from content/profile.json — do not edit by hand.
     Every entry needs a lastmod, and none may be dated in the future;
     tests/content.test.js checks both. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

// ------------------------------------------------------------------
// voice-scripts.js
// ------------------------------------------------------------------
function renderVoiceScripts(data) {
    const comment = data.narration.$comment.map(l => (l ? `// ${l}` : '//')).join('\n');

    // JSON.stringify gives a correctly escaped JS string literal, which is
    // what keeps the text byte-identical through the round trip — and the
    // narration hashes with it.
    const scripts = data.narration.scripts.map(s => `        {
            id: ${JSON.stringify(s.id)},
            label: ${JSON.stringify(s.label)},
            text: ${JSON.stringify(s.text)}
        }`).join(',\n');

    return `// ===================================================================
// GENERATED by ${GENERATED_BY} from content/narration.json.
// Do not edit this file — your changes will be overwritten.
// Edit content/narration.json, then run: npm run build:content
//
${comment}
// ===================================================================
(function (root, factory) {
    const data = factory();
    root.VoiceScripts = data;
    if (typeof module !== 'undefined' && module.exports) module.exports = data;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
    // \`id\` doubles as the audio filename: assets/audio/<id>.mp3
    // \`label\` is the accessible name of the play button for that section.
    const SCRIPTS = [
${scripts}
    ];

${SPLIT_SENTENCES}

    const byId = {};
    SCRIPTS.forEach(s => { byId[s.id] = s; });

    return { SCRIPTS, byId, splitSentences };
});
`;
}

// The sentence splitter is behaviour, not content, so it is not expressed as
// data. It is carried here byte-for-byte from the hand-written file this
// generator replaced — rewriting it would have quietly changed how the
// narration is chunked, and tests/bugs.test.js exists because that has bitten
// this repository before.
const SPLIT_SENTENCES = String.raw`    // Sentence splitting, shared by the player (for utterances and captions)
    // and available to the generator.
    //
    // Splitting naively on "." mangles these scripts, which are full of
    // spelled-out initialisms — A.I., E.S.G., Q.G.I.S., Arc.G.I.S. Those are
    // parked behind a sentinel before the split and restored after, so
    // "sustainable A.I. — making sure…" stays a single sentence.
    //
    // The sentinel is deliberately non-numeric: the scripts are also full of
    // real numbers (164 water points) that must survive the round trip
    // untouched. tests/bugs.test.js asserts exactly that.
    // ---------------------------------------------------------------
    const INITIALISM = /[A-Za-z]+(?:\.[A-Za-z])+\./g;

    function splitSentences(text) {
        const parked = [];
        const masked = String(text).replace(INITIALISM, (m) => {
            parked.push(m);
            return ` + '`@@${parked.length - 1}@@`' + String.raw`;
        });
        const restore = s => s.replace(/@@(\d+)@@/g, (_, i) => parked[Number(i)]);
        const raw = masked.match(/[^.!?…]+[.!?…]+["'”’—]?\s*/g) || [masked];

        // Fold very short fragments into the previous sentence — a two-word
        // utterance reads as a stutter and costs an extra engine round-trip.
        const out = [];
        raw.map(s => restore(s).trim()).filter(Boolean).forEach(s => {
            if (out.length && s.length < 40) out[out.length - 1] += ' ' + s;
            else out.push(s);
        });
        return out.length ? out : [String(text)];
    }`;

// ------------------------------------------------------------------
// index.html — the JSON-LD block only
// ------------------------------------------------------------------
const LD_START = '    <!-- JSON-LD:START — generated by scripts/build-content.js from content/profile.json. Do not edit by hand. -->';
const LD_END = '    <!-- JSON-LD:END -->';

function renderJsonLd(data) {
    const { profile } = data;
    const ld = {
        '@context': 'https://schema.org',
        '@type': 'Person',
        name: profile.person.name,
        jobTitle: profile.person.jobTitle,
        url: profile.links.site,
        image: `${SITE}assets/img/profile.webp`,
        email: `mailto:${profile.person.email}`,
        worksFor: {
            '@type': 'Organization',
            name: profile.currentRole.organization,
            parentOrganization: profile.currentRole.parentOrganization
        },
        address: {
            '@type': 'PostalAddress',
            addressLocality: profile.person.locality,
            addressCountry: profile.person.country
        },
        alumniOf: profile.education.map(e => ({ '@type': 'CollegeOrUniversity', name: e.institution })),
        knowsAbout: profile.knowsAbout,
        sameAs: [profile.links.github, profile.links.linkedin]
    };

    // Entities are NOT escaped: a script block of type application/ld+json is
    // raw text, and "&amp;" inside it reaches a consumer literally.
    const body = JSON.stringify(ld, null, 4)
        .split('\n')
        .map(line => `    ${line}`)
        .join('\n');

    return `${LD_START}
    <script type="application/ld+json">
${body}
    </script>
${LD_END}`;
}

function injectJsonLd(data) {
    const file = path.join(ROOT, 'index.html');
    const html = fs.readFileSync(file, 'utf8');
    const start = html.indexOf(LD_START);
    const end = html.indexOf(LD_END);
    if (start === -1 || end === -1) {
        throw new Error('index.html is missing the JSON-LD:START / JSON-LD:END markers');
    }
    return html.slice(0, start) + renderJsonLd(data) + html.slice(end + LD_END.length);
}

// ------------------------------------------------------------------
// Write or check
// ------------------------------------------------------------------
function main() {
    let data;
    try {
        data = content.loadAll();
    } catch (err) {
        console.error(`\n  ${err.message}\n`);
        process.exit(1);
    }

    // One fully-rendered page per lens, plus the default. No query strings,
    // no client-side selection, nothing to fail with scripting off.
    const lensPages = [data.lenses.default].concat(data.lenses.lenses)
        .map(lens => [lensPage(lens.id), renderCaseStudies(data, lens)]);

    const outputs = lensPages.concat([
        ['research.html', renderResearch(data)],
        ['sitemap.xml', renderSitemap(data)],
        ['voice-scripts.js', renderVoiceScripts(data)],
        ['index.html', injectJsonLd(data)]
    ]);

    const stale = [];
    outputs.forEach(([rel, next]) => {
        const file = path.join(ROOT, rel);
        const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;

        if (current === next) {
            console.log(`  · ${rel.padEnd(20)} up to date`);
            return;
        }
        if (CHECK) {
            stale.push(rel);
            console.log(`  ✗ ${rel.padEnd(20)} OUT OF DATE`);
            return;
        }
        fs.writeFileSync(file, next);
        console.log(`  → ${rel.padEnd(20)} ${current === null ? 'created' : 'updated'}`);
    });

    if (CHECK && stale.length) {
        console.error(`\n  ${stale.length} generated file(s) do not match content/.`);
        console.error('  Run: npm run build:content   (and commit the result)\n');
        process.exit(1);
    }

    console.log(`\n  ${data.projects.caseStudies.length} case studies · ${data.research.outputs.length} research outputs · ${data.lenses.lenses.length} lenses\n`);
}

main();
